### ISSUE TITLE
PostgreSQL support?

### ISSUE THREAD

**Issue by poVoq** [documize/community#100]
see title, would be nice, especially for those running either only that and/or a mariadb on the same server already.

**Comment by HarveyKandola** [comment]
Agreed.

Had planned to go with MariaDB in last release but their JSON implementation was not compatible with MySQL 5.7.10+ !!

Nonetheless, we're working on supporting BOTH PostgreSQL and MySQL.

**Comment by enoch85** [comment]
@HarveyKandola Any ETA for this?

**Comment by HarveyKandola** [comment]
Big two pieces of work lined up next:

1. MS SQL and PostgreSQL support
2. LDAP integration (without Keycloak)

Before that:

1. Content analytics and reporting
2. Jira Connector

That's the plan for the coming couple of months

**Comment by enoch85** [comment]
Great news!

**Comment by fire** [comment]
What is the status of the Postgres integration?

**Comment by HarveyKandola** [comment]
Referring to the previous plan (in above comments), we have completed:

1. Content analytics and reporting
2. Jira Connector
3. Native LDAP/AD sync/auth

Point 3 rolls out tomorrow.

So next is PostgreSQL!

**Comment by enoch85** [comment]
@HarveyKandola Do you have any ETA for when that is released?

**Comment by HarveyKandola** [comment]
4 to 8 weeks.

**Comment by enoch85** [comment]
@HarveyKandola Will it be possible to migrate easily for users running on MariaDB/MySQL?

**Comment by HarveyKandola** [comment]
Will know in a couple of weeks time as we get deeper into the process.

Database migrations are rarely straightforward!

**Comment by enoch85** [comment]
> Database migrations are rarely straightforward!

[It depends](https://www.techandme.se/we-migrated-to-postgresql/). :)

**Comment by HarveyKandola** [comment]
Added support for PostgreSQL.

Seems like a better full text search experience for better content search results!

**Comment by fire** [comment]
Seems like cockroachdb (postgresql) compatible should work if one removes the GIN indexes. 
https://www.cockroachlabs.com/

**Comment by HarveyKandola** [comment]
@fire sounds too good to be true!

**Comment by fire** [comment]
When do you expect to have a release?

I can report problems with Cockroachdb. Cockroachdb is an one executable application that runs on most platforms including Windows.

A further look shows Crdb has GIN support too. https://www.cockroachlabs.com/docs/stable/inverted-indexes.html#creation

You can try crdb too, I'm not sure how to build documize. Since both applications are single executable golang binaries, it may be cool to show demos using the combination.

**Comment by HarveyKandola** [comment]
@fire we plan to fire out nightly build some time next week -- will update this thread so you can try it and report back.

**Comment by fire** [comment]
https://gist.github.com/fire/56c203eb7302027f3e9d375a4e0c5997/revisions Except for the full text search (see commented out code) this schema is able to be created in cockroachdb.

**Comment by HarveyKandola** [comment]
@fire thanks for the lowdown -- much appreciated!

I suspect we will roll out Microsoft SQL Server support before CockroachDB.

**Comment by HarveyKandola** [comment]
Nightly build...

Community Edition:

https://storage.googleapis.com/documize/downloads/nightly/documize-community-darwin-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-community-linux-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-community-windows-amd64.exe

Enterprise Edition:

https://storage.googleapis.com/documize/downloads/nightly/documize-enterprise-darwin-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-enterprise-linux-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-enterprise-windows-amd64.exe 

Docs:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide
