### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by HarveyKandola** [documize/community#102]
Multiple requests for MariaDB as it becomes the default on multiple Linux distro's -- also see #100

**Comment by pzduniak** [comment]
I made some changes to integrate Documize with a product that I am working on. That includes a hacked together MariaDB support and support for utf8mb4 encoding (seriously, *do not* ever use the "classic" utf8, it's a 7-bit encoding with weird behaviour).

You can check it out at https://github.com/portablecloud/documize. I did not see a better way to get MariaDB working, if you have any ideas then please tell me, we will contribute the changes per the license.

**Comment by HarveyKandola** [comment]
@pzduniak thanks so much for the this!

We have just finished a major down payment of tech debt and will integrate back into master branch in the coming days. Refactored. Restructured.

We will then provide MariaDB and other DB support out-of-the-box -- your approach will come intto play. 

Great call on utf8 vs. utf8mb4 -- will follow suit.

Will update this ticket when officially ready.

**Comment by HarveyKandola** [comment]
Done.
