### ISSUE TITLE
No way to create documents.

### ISSUE THREAD

**Issue by cetra3** [documize/community#103]
Just tried downloading both community and enterprise versions, both don't appear to work.  Not sure if I have missed a step here or there is something I fundamentally don't get.

## Environment:

* Mac OSX
* Chrome 59.0.3071.115

## Steps to replicate:

* Install mysql from homebrew
* Create blank mysql database:

```
create database documize;
grant all on documize.* to 'documize'@'localhost' identified by 'documize';
```

* Download either community `1.49.2` from releases here, or the enterprise
* Run the following command:

```
./documize-community-darwin-amd64 -port=5001 -db='documize:documize@tcp(localhost:3306)/documize'
```

* Navigate to http://localhost:5001
* Sign up with username/password

* Create a space
* Click on the space
* Notice nothing happens..

**Comment by cetra3** [comment]
Cheers for the quick turnaround

**Comment by HarveyKandola** [comment]
Just prep'ing new releases...

**Comment by HarveyKandola** [comment]
Try this...

https://github.com/documize/community/releases/tag/v1.50.0

**Comment by sogen** [comment]
Hi, can't create documents on 1.50.1

**Comment by HarveyKandola** [comment]
Can you try this download and try a Word import?

https://documize.com/downloads
