### ISSUE TITLE
insert image

### ISSUE THREAD

**Issue by fedenolasco** [documize/community#106]
![2017-07-29_1157_documize_insert_image](https://user-images.githubusercontent.com/15969594/28744283-3dd0c54c-7455-11e7-960a-a44d131df4fa.png)

Hi I am using 1.50.1 community edition under Windows 10 operating system.

I have tried different way to insert an image, but instead of the image I get a placeholder. 

Can you document how to insert an image. Seems to not work for me.

Fede.

**Comment by fedenolasco** [comment]
Hi, just to confirm that copy / paste works, but insert image via above dialogue window doesn't for me.

**Comment by HarveyKandola** [comment]
We're looking into it now...

**Comment by abdulrhman0** [comment]
The issue was related to CDN.

Some elements of the image uploader and the wysiwyg content editor are served from within your ‘skin’ directory – which is now served from your CDN, and will start throwing cross domain errors.

**Comment by HarveyKandola** [comment]
We've implemented "upload selected image file and insert into editor" functionality.

This is in addition to the existing image drag-drop and clipboard-paste support.
