### ISSUE TITLE
go: unknown subcommand "generate"

### ISSUE THREAD

**Issue by fmakowski** [documize/community#107]
Dear Documize community,

I have recently decided to install the Documize Community edition on my Raspberry Pi, but it seems, that I cannot use the supplied binary from the `releases` page, since I have the following error:

    ./documize-community-linux-amd64: cannot execute binary file: Exec format error

Which I assume comes from the fact, that I am running 32bit system on my Raspberry Pi, and it cannot handle the binary, which is surely 64bit. 

For that reason, I have decided to build the project myself, but I am having trouble setting it up. My current issue can be defined as following terminal output when running `./build.sh`:

```
Copying Ember assets...
cp: cannot stat ‘gui/dist-prod/assets’: No such file or directory
cp: cannot stat ‘gui/dist-prod/codemirror’: No such file or directory
cp: cannot stat ‘gui/dist-prod/tinymce’: No such file or directory
cp: cannot stat ‘gui/dist-prod/sections’: No such file or directory
cp: cannot stat ‘gui/dist-prod/*.*’: No such file or directory
cp: cannot stat ‘gui/dist-prod/favicon.ico’: No such file or directory
Generating in-memory static assets...
go: unknown subcommand "generate"
Run 'go help' for usage.
Compiling app...
Compiling documize-community-darwin-amd64
flag provided but not defined: -asmflags
(...)
```
So my question is, do I have some incompatible Go compiler or am I doing something wrong? 

Best regards!
Filip

**Comment by HarveyKandola** [comment]
Which version of Go have you installed/compiling with?

**Comment by fmakowski** [comment]
```
$ go version
go version go1.3.3 linux/arm
```
Ok, so it seems that the version installed by `apt-get install golang` on Raspbian 8 is kind of the old one.

I have installed 1.8 using your guide and now it is working fine. Still, I am encountering following error:

```
./gocode/src/github.com/documize/community/core/api/endpoint/keycloak.go:23:2: cannot find package "obiwan/utility" in any of:
        /home/fmak/gocode/src/github.com/documize/community/vendor/obiwan/utility (vendor tree)
        /usr/local/go/src/obiwan/utility (from $GOROOT)
        /home/fmak/gocode/src/obiwan/utility (from $GOPATH)
```

Any ideas on how to solve that? (I have encountered similar for `go-sql-driver/mysql` but this I solved by cloning github repo to `gocode/src` properly)

Thank you!
Best regards,
Filip

**Comment by HarveyKandola** [comment]
That is a rogue package reference!

Have removed and committed to master -- please test again.
