### ISSUE TITLE
1password Chrome extension not triggered by password change

### ISSUE THREAD

**Issue by andreis** [documize/community#108]
Pretty much what the title says. Normally I'd see the 1password extension pop up and ask me to create or update a login, but this doesn't happen when changing my password on our local install. Usually the culprit is using non standard forms/UI elements.

**Comment by HarveyKandola** [comment]
Thanks for the report @andreis 

I personally use Dashlane and that works just fine.

Nonetheless, we'll track down the issue with 1Password and fix.
