### ISSUE TITLE
GitHub section should be configurable from a UI

### ISSUE THREAD

**Issue by pzduniak** [documize/community#110]
You're probably aware of the issue.

1) I created a Docker image from my MariaDB-supporting fork.
2) Deployed it on Rancher with custom converter and a MariaDB instance.
3) Configured as much as I could except SMTP.
4) Tried to create a GitHub section, the UI showed for a while and then I got redirected to a GitHub's 404 page:

```https://github.com/login/oauth/authorize?client_id=&scope=repo&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fapi%2Fpublic%2Fvalidate%3Fsection%3Dgithub&state=https%3A%2F%2Fdocumize.portablecloud.net...```

5) Spent like 20 minutes looking for the solution just to find out that you have to run commands on the databse to configure it.

This is pretty bad and the solution is pretty simple. I really like all things Go and would love to run only Go in our edtech deployments, but the applications that we provide must be _reasonable enough_. While the UI intuitiveness is pretty bad (it took me way too long to figure most of the functionality), the rest is great. Good job!

**Comment by HarveyKandola** [comment]
Yup, GitHub setting needs UI access -- will get it done!
