### ISSUE TITLE
It is not clear whether feedback and other features are available in Community Edition

### ISSUE THREAD

**Issue by pzduniak** [documize/community#111]
https://docs.documize.com/s/WOzFU_MXigAB6sIH/user-guides/d/WOyxLfMXigAB6sGS/assigning-document-actions-feedback-review-contributions

I can't see all that stuff in my deployment, so I assume that they are only in EE. Am I right?

**Comment by HarveyKandola** [comment]
You are right, Enterprise Edition only.

And yes, we can and will do a better job of explaining the difference.

Sorry for the hassle.
