### ISSUE TITLE
Allow passing the conversion endpoint as a CLI flag

### ISSUE THREAD

**Issue by pzduniak** [documize/community#112]
We're integrating Documize with our "local cloud" platform that's supposed to fully work offline. In order to finish "packing it up into an app", I need a way to pass the conversion server's URL as a CLI parameter / environment variable. Could you please add such thing?

**Comment by HarveyKandola** [comment]
Just to be clear -- you can set the Conversion API endpoint through the admin UI.

But I guess you already know that and really need CLI pass-thru?

**Comment by pzduniak** [comment]
Precisely, I am deploying everything using a docker-compose-like manifest and need everything to integrate nicely.

**Comment by HarveyKandola** [comment]
Understood, thank you.

The Conversion API endpoint is per tenant and command line switches apply to all tenants. Hence the mismatch.

See this document to understand tenants: 

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO4Rm_MXigAB6sLP/managing-documize

However, that is not to say it cannot/should not be done. 

It's easy enough to do, but we just need to ensure that command line switches are consistent and logical. Thoughts welcome.
