### ISSUE TITLE
 Where are the attachments stored? Could it be configurable?

### ISSUE THREAD

**Issue by pzduniak** [documize/community#113]
I think that's the last issue, you can attach images in the CE, where are they stored? Can the location be configurable? I am running Documize in Docker and would like to have persistent attachments.

**Comment by HarveyKandola** [comment]
They are stored inside the SQL database.

Nothing is stored on the file system.

**Comment by pzduniak** [comment]
I suppose it's fine this way, but I'd recommend having alternative methods of storage. Possibly an OpenStack Swift / S3 backend?

**Comment by HarveyKandola** [comment]
Agreed.

Hence we have just completed pluggable persistence layer -- implement custom database/storage providers. Should be in master branch this week.
