### ISSUE TITLE
Blank Page After Setup

### ISSUE THREAD

**Issue by Beltasbur** [documize/community#116]
Hello there,

I'm encountering an empty page after I click "Setup" button in /setup. After that, it goes to /auth/sso/<key> but then nothing happens.

Here's my console:
![putty_2017-08-26_14-34-00](https://user-images.githubusercontent.com/2662700/29740957-9fccaa96-8a6b-11e7-8d61-b2ff843431ca.png)

What should I do? I installed MySQL as required, then tried to setup Documize. Is there any other requirement? Trying to browse Documize doesn't work either, no any data from the console.

Edit: Documize throws out errors when I restart:
![putty_2017-08-26_14-37-17](https://user-images.githubusercontent.com/2662700/29740992-2441f47a-8a6c-11e7-952f-85baf34fb955.png)

**Comment by HarveyKandola** [comment]
Can you try latest release please and clear your database?

**Comment by Beltasbur** [comment]
Hello there,

Unfortunately, with the latest release (1.55.1), it's still the same. I also tried to build Community Edition from source, but binary files doesn't appear anywhere.

![putty_2017-08-28_17-20-09](https://user-images.githubusercontent.com/2662700/29777556-2c477762-8c15-11e7-908c-d84201636540.png)

Here's the console screenshots for the latest release, still showing blank/unresponsive pages.

![putty_2017-08-28_15-54-38](https://user-images.githubusercontent.com/2662700/29777619-51982c3c-8c15-11e7-858d-9225ac036b94.png)

This is the output if I restart the binary:

![putty_2017-08-28_15-54-44](https://user-images.githubusercontent.com/2662700/29777621-5199ea2c-8c15-11e7-884d-ccd3344249e3.png)

Also, this is the output when I run ./build.sh

![putty_2017-08-28_17-12-42](https://user-images.githubusercontent.com/2662700/29777650-6e56f9de-8c15-11e7-8374-edb2ca2211a0.png)

**Comment by HarveyKandola** [comment]
In terms of compiling from source, you seem to have two issues:

1. As per the console output, see https://ember-cli.com/user-guide/#watchman to resolve watchman issue.
2. You might need to upgrade your installed version of Go: https://golang.org/dl/

Once you have it compiling, we can resolve other issues accordingly.

**Comment by Beltasbur** [comment]
Hello again, I'm sorry that I couldn't make the compiling work. So I have tried my chances again with a fresh Ubuntu 16.04.3 x64 Server on DigitalOcean, but this time, things get weirder.

This is the console after I press "Setup" button.

![putty_2017-08-30_01-29-54](https://user-images.githubusercontent.com/2662700/29847256-6270a26e-8d23-11e7-9364-8a42e662257f.png)
![putty_2017-08-30_01-30-23](https://user-images.githubusercontent.com/2662700/29847257-62732d72-8d23-11e7-95c9-29a7757d2df4.png)
![putty_2017-08-30_01-30-29](https://user-images.githubusercontent.com/2662700/29847258-627534aa-8d23-11e7-8b59-dc4de60bcf0d.png)

**Comment by HarveyKandola** [comment]
Thanks for the detailed report -- we have finally managed to replicate the issue on Ubuntu and are working on resolving this ASAP.

**Comment by HarveyKandola** [comment]
Please try latest release as we think the issue has been resolved.

On Ubuntu, MySQL can return non-standard version information and hence we have:

1. Improve database detection 
2. Added new optional "dbtype" command line switch which can be set to mysql|percona|mariadb (environment variable name is DOCUMIZEDBTYPE)

Trash your database and try again.
