### ISSUE TITLE
boltdb or badger db ?

### ISSUE THREAD

**Issue by gedw99** [documize/community#122]
sorry to be a pain but i cant use non golang DB'S.

I used to use mysql and oracle but when you have a decent event bus, which you also have, the DB become less of a bottleneck i have found.

SO i was wondering if BoltDB or Badger is welcome ?

Badger is very fast 
https://blog.dgraph.io/post/badger-txn/

Its also supported in Bleve with a recent port from boltDB to Badger
https://github.com/akhenakh/bleve/tree/badger/index/store/badger

BoltDB as we all know is the tried and true stable goang db with poor write perf, unless batching.

**Comment by HarveyKandola** [comment]
Both are welcome as Documize has pluggable persistence storage providers.

Not sure we will tackle these any time soon as next up is MS SQL and PostgreSQL

**Comment by gedw99** [comment]
Ok. I guess i will have to use CockroachDB, which is PostgreSQL compatible and golang based.

**Comment by HarveyKandola** [comment]
See #100
