### ISSUE TITLE
When editing Space Permissions, the checkboxes do not refresh with the current space

### ISSUE THREAD

**Issue by ADTC** [documize/community#124]
**Steps:**
1. Create two spaces.
1. Edit the permissions of one space (make a mental note of the default permissions).
1. Save permissions and switch to the second space.
1. Edit the permissions of the second space.

**Expected result:**
Permission checkboxes show the second space's current permissions.

**Current result:**
Permission checkboxes cache and show the first space's saved permissions. Reloading the entire page would load the second space's current permissions.

**Browser:** Chrome Version 61.0.3163.100

**Comment by ADTC** [comment]
It's me Arun btw

**Comment by HarveyKandola** [comment]
Please can you try with the latest version that was released today?
