### ISSUE TITLE
Unable to Install due to mysql wrong version

### ISSUE THREAD

**Issue by s3rv3rn3rd** [documize/community#125]
currently losing hair on this because no matter what I do the documize installer tells me that I've got the wrong version of mysql.

I've got a separate mySQL server named mysql01. Originally it was on 5.7 or something around there so I updated it. When it was on mysql 5.X the documize installerd identified it correctly. I upgraded to version 10.1. When it said it needed to be on 10.3, so I upgraded to 10.3. Now, it keeps saying I'm on 10.2.58 but if you do a mysql -V on the mysql server it's very clearly 10.3.2.

Am I missing something?

**Comment by HarveyKandola** [comment]
MySQL or MariaDB?

**Comment by s3rv3rn3rd** [comment]
It's Centos 7 and when I had version 5.X it showed as MariaDB, as normal with CentOS. Now that I've upgraded to 10, it shows MySQL

**Comment by HarveyKandola** [comment]
MariaDB versioning is 10.x whereas MySQL versioning is like 5.x -- maybe the dbtype switch will help Documize:

`-dbtype="mariadb"`

[Switch docs](https://docs.documize.com/s/VzO9ZqMOCgABGyfW/VzO9ZqMOCgABGyfW/d/VzSL8cVZ4QAB2B4Y/VzSL8cVZ4QAB2B4Y
)

**Comment by s3rv3rn3rd** [comment]
Hmm - I tried that but I'm getting the same error

**Comment by s3rv3rn3rd** [comment]
I've got the MySQL server on a separate VM and when I do it that way, it doesn't work (although it's working fine for several other apps I have). So I decided to just install MySQL on the local box ... and it works fine. This is not my preferred method for doing this. Any reason this doesn't work when having the MySQL data on a separate server?

**Comment by HarveyKandola** [comment]
No reason why separate VM would not work.

Sounds like network/access issue.
