### ISSUE TITLE
Add support for newlines to be treated as <br> in markdown section

### ISSUE THREAD

**Issue by uchti** [documize/community#129]
First of all, I want to thank you for your project.
I noticed a wrong parsing of new lines in the markdown section.
To saved a new line requires double tap to return. 
Please correct this. I hope this does not take long.

**Comment by HarveyKandola** [comment]
Thanks for the report -- we will look into this for next release.

**Comment by sauls8t** [comment]
This is by design as per spec:
 
https://spec.commonmark.org/dingus/
