### ISSUE TITLE
Logging in runtime

### ISSUE THREAD

**Issue by tamvcspk** [documize/community#130]
How can I print logs when documize is running, like errors, event, or request...

**Comment by HarveyKandola** [comment]
Documize currently logs errors, etc. to STDOUT if that is what you are asking.

**Comment by tamvcspk** [comment]
Thanks, this is what I've got so far and it works:
`START /B documize-community-windows-amd64.exe -port=5001 -db=username:password@tcp(localhost:3306)/documize -dbtype=mysql -salt=yoursalt 2>&1 1>logs\output.txt`

**Comment by HarveyKandola** [comment]
Great!

If you run Documize within a Docker container you can get Docker to write the logs to a Syslog service like Papertrail.

    --log-driver=syslog --log-opt syslog-address=udp://papertrail-url-port

Hope this helps!
