### ISSUE TITLE
Import Document Seems Broken

### ISSUE THREAD

**Issue by samagnew** [documize/community#132]
Running in a CentOS 7 container in Docker Swarm behind Nginx Web proxy (documize is port 80, https handled by Nginx). I have tried 1.55.0, 1.56.0 and 1.57.0 (1.56.1 wouldn't run for me).

I seem to have full functionality and have successfully created spaces, configured access, created new documents from "Empty document". However, upon attempting "Import document" I get the "converting document..." feedback but nothing subsequently happens. No converted document or notice ever appears. Tried, xlsx, doc, svg...

Half the time there is nothing at all in documize log. Half the time this:
Org Advanced Computing (Wnqc-m96XAAS68iP) [Uploaded] FARF_110324_VPN_SCWEBs.doc
Starting conversion of document:  FARF_110324_VPN_SCWEBs.doc
Finished converting document:  FARF_110324_VPN_SCWEBs.doc
conversion.upload
Invalid license
goroutine 338 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc420146280, 0x0, 0xb470ca, 0x11, 0xea6240, 0xc4203c0160)
	src/github.com/documize/community/edition/logging/logger.go:51 +0x17f
github.com/documize/community/edition/logging.(*Logger).Error(0xc42014e460, 0xb470ca, 0x11, 0xea6240, 0xc4203c0160)
	<autogenerated>:1 +0x75
github.com/documize/community/domain/conversion.(*Handler).convert(0xc42015e480, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031ee00, 0xc420014630, 0x24, 0xc420018318, 0x10, 0xc420014630, 0x24, ...)
	src/github.com/documize/community/domain/conversion/conversion.go:121 +0x9d7
github.com/documize/community/domain/conversion.(*Handler).UploadConvert(0xc42015e480, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031ee00)
	src/github.com/documize/community/domain/conversion/endpoint.go:37 +0x173
github.com/documize/community/domain/conversion.(*Handler).UploadConvert-fm(0x7f0df9c7b4c8, 0xc420160640, 0xc42031ee00)
	src/github.com/documize/community/server/routing/routes.go:86 +0x48
net/http.HandlerFunc.ServeHTTP(0xc42024a6b0, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031ee00)
	/usr/local/Cellar/go/1.9.4/libexec/src/net/http/server.go:1918 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420206c60, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031ee00)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:133 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f0df9c7b4c8, 0xc420160640, 0xc42031ec00, 0xc420b40840)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42039fcc0, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031ec00, 0xc420b40840)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xea8100, 0xc42039fcc0, 0xc42039fd20, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031ec00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7f0df9c7b4c8, 0xc420160640, 0xc42031ec00)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0x60
github.com/documize/community/server.(*middleware).Authorize(0xc42024a460, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031e700, 0xc420b40300)
	src/github.com/documize/community/server/middleware.go:193 +0x20d
github.com/documize/community/server.(*middleware).Authorize-fm(0x7f0df9c7b4c8, 0xc420160640, 0xc42031e700, 0xc420b40300)
	src/github.com/documize/community/server/server.go:70 +0x52
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc42024b140, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031e700, 0xc420b40300)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:24 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xea8100, 0xc42024b140, 0xc42039fd00, 0x7f0df9c7b4c8, 0xc420160640, 0xc42031e700)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:33 +0xa5
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc4203e4750, 0x7f0df9c7b4c8, 0xc420160600, 0xc42031e700)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:73 +0x100
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420206120, 0x7f0df9c7b4c8, 0xc420160600, 0xc42031e700)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:133 +0xed
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f0df9c7b4c8, 0xc420160600, 0xc42031e300, 0xc420b402e0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:41 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc4203fba20, 0x7f0df9c7b4c8, 0

**Comment by samagnew** [comment]
It is community edition and seems to know that it is...
Database checks: SQL version 10.3.4-MariaDB
Database locked by this Documize instance
Database checks: last applied db_00017.sql
Database checks: no updates required
Database checks: completed
Registered 10 sections
Starting Community Edition version 1.57.0
Starting web server
Starting non-SSL server on 80
[negroni] listening on :80

**Comment by sauls8t** [comment]
Community edition does not support Word importing and conversion (yet!). Will be resolved soon.

Sorry for the confusion.

If you need Word conversion then feel free to use the free Enterprise Edition 

Enterprise and Community both work/share the same database schema, so you can move between them.

**Comment by sauls8t** [comment]
Link for download:

https://documize.com/downloads

Differences:

https://documize.com/pricing

**Comment by sauls8t** [comment]
@samagnew we just updated the platform to allow Community edition Word importing

**Comment by HarveyKandola** [comment]
Agreed on wording.

Correct, support for Markdown/Word but not XLS/PDF/PPT.

**Comment by samagnew** [comment]
Switched to EE (1.59.0). Obtained and applied license. Import still not doing anything. Self-hosted the conversion container and pointed to it. Document conversion now working for type DOC. License accepted as Enterprise. But still no response at all to attempted xlsx import. Nothing in logs on documize or conversion container. So, still seems broken

Database checks: started
Database checks: SQL variant MariaDB
Database checks: SQL version 10.3.4-MariaDB
Database locked by this Documize instance
Database checks: last applied db_00017.sql
Database checks: no updates required
Database checks: completed
Registered 10 sections
Starting Enterprise Edition version 1.59.0
Starting web server
Starting non-SSL server on 80
[negroni] listening on :80
Processing Enterprise Edition license
License: {Name:Weill Cornell Medicine in Qatar Email:saa2012@qatar-med.cornell.edu Edition:Enterprise Start:2018-02-18 07:58:22.024344054 +0000 UTC End:2019-02-17 07:58:22.024344328 +0000 UTC Seats:5 Trial:false Valid:true}

Sam

**Comment by HarveyKandola** [comment]
Excel not supported!

Neither is PDF or PPT.

**Comment by samagnew** [comment]
My confusion. I thought Community not supporting these but Enterprise did. So DOC and MD only for CE and EE both then.

**Comment by HarveyKandola** [comment]
Correct, Markdown & Word for both.

You should be able to point to https://api.documize.com for Markdown/Word import support, especially if your Documize instance URL is publically accessible.

FYI, edited your comment above to remove email address and license details!

**Comment by chorylee** [comment]
> Correct, Markdown & Word for both.
> 
> You should be able to point to https://api.documize.com for Markdown/Word import support, especially if your Documize instance URL is publically accessible.
> 
> FYI, edited your comment above to remove email address and license details!

I have the same issue and fix it by pointing to https://api.documize.com. But it means that some secret imported document will become open to documize. Really worry about the my company's privacy...

**Comment by HarveyKandola** [comment]
@chorylee feel free to host the conversion process in-house as per:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/customizing-documize?currentPageId=WS3-rjltKgABVdLe&source=Conversion

**Comment by chorylee** [comment]
> @chorylee feel free to host the conversion process in-house as per:
> 
> https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/customizing-documize?currentPageId=WS3-rjltKgABVdLe&source=Conversion

@HarveyKandola , many thanks for your quick sharing.
