### ISSUE TITLE
documize 1.59.3-ee doesn't recognise license

### ISSUE THREAD

**Issue by samagnew** [documize/community#134]
Same license I have been using up until update to 1.59.3 (saa2012@qatar-med.cornell.edu)

License: {Name:Weill Cornell Medicine in Qatar Email:saa2012@qatar-med.cornell.edu Edition:Enterprise Start:2018-02-18 07:58:22.024344054 +0000 UTC End:2019-02-17 07:58:22.024344328 +0000 UTC Seats:5 Trial:false Valid:false}

Will revert to ce in meantime

Sam

**Comment by HarveyKandola** [comment]
@samagnew 

Can you grab a new license and try with EE?

https://documize.com/downloads

**Comment by samagnew** [comment]
Confirmed. Thanks
