### ISSUE TITLE
Feature Request: Show new content upon clicking Content tab

### ISSUE THREAD

**Issue by samagnew** [documize/community#135]
This request is from a collaborating user.

Reproduce:
1. In content tab user 1 edits a document section
2. The change is saved with save button by user 1
3. User 2 is viewing the same document in the content tab
4. After first user 1's "save" if user 2 goes to revisions tab they immediately see new revision
5. However, when user 2 clicks again on content tab they don't see the new content (they must refresh the page using the browser refresh)

The request is that clicking on the "content" tab should always fetch the most current revision of text

Sam

**Comment by sauls8t** [comment]
Makes sense -- added to the development pipeline!

**Comment by HarveyKandola** [comment]
Will be in next release (probably w/c 12th March 2018)
