### ISSUE TITLE
Add support to merge document

### ISSUE THREAD

**Issue by sterrling** [documize/community#138]
Please add a new feature to merge different documents into one document (page).

**Comment by sauls8t** [comment]
To be clear:

Merge one document into another document, so that target document contains all pages/sections, and other (empty) document is removed.

Right?

We can do this no problem for release after next (as next release is due tomorrow).

**Comment by sterrling** [comment]
Exactly! Thanks a lot!

**Comment by sauls8t** [comment]
Thanks for confirming.

We have scheduled for development. One of the team will respond to this issue when feature is completed.

**Comment by sauls8t** [comment]
Completed for next release.
