### ISSUE TITLE
Add native LDAP support

### ISSUE THREAD

**Issue by enoch85** [documize/community#139]
I couldn't see that LDAP is supported anywhere? Would be nice to have as it's much easier to integrate with current setup when running Windows AD.

**Comment by mcmatts** [comment]
You can connect to LDAP using Keycloak at the moment.

Direct/native LDAP connector coming in about 12 weeks time.

**Comment by enoch85** [comment]
> Direct/native LDAP connector coming in about 12 weeks time.

So 12 weeks has soon passed. Any update on this?

Btw, thank you for your awesome work on this! Looking forward to implement it in our company once LDAP and PostgreSQL is live.

**Comment by mcmatts** [comment]
@enoch85 nor sure, I will check with @HarveyKandola and the team!

**Comment by enoch85** [comment]
@mcmatts Any ETA yet?:)

**Comment by enoch85** [comment]
@HarveyKandola Sorry for bumping this again. I sent you a response to the email you sent me, but I haven't heard anything from you yet. 

Is there anything I can do to speed up the process?

**Comment by sauls8t** [comment]
Have chased up for you -- someone will follow-up our side.

**Comment by HarveyKandola** [comment]
@sauls8t has completed -- out very very soon!
