### ISSUE TITLE
Error while exporting to PDF

### ISSUE THREAD

**Issue by enoch85** [documize/community#145]
Using the Enterprise version (don't know where to report issues for that) I got this while exporting to PDF:

`SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data`

### Database
Server version: 10.3.5-MariaDB-10.3.5+maria~xenial-log mariadb.org binary distribution

### Server
Ubuntu Server 16.04.4

**Comment by HarveyKandola** [comment]
We're looking into this right now...

**Comment by enoch85** [comment]
I :heart: your support!

**Comment by sauls8t** [comment]
@enoch85 we think we found the issue -- @HarveyKandola is just pushing up new Docker container v1.8.2 and will update this issue when live so you can test again.

**Comment by HarveyKandola** [comment]
Pushed live!
