### ISSUE TITLE
[Feature Request] Print sections and not the whole site

### ISSUE THREAD

**Issue by enoch85** [documize/community#146]
We are testing the enterprise version and got a request to print only sections, and not the whole page.

Would that be possible to implement?

**Comment by HarveyKandola** [comment]
It's possible.

We have also been asked to implement per section comments as well, and we plan to tackle that next week. Happy to add this to the same sprint.

Related thoughts:

* Select one or more sections
* Email them
* Print them
* Export them

Thoughts welcome.

**Comment by enoch85** [comment]
I think that's a good starting point. Let's see how it develops and I can give you further input later on.

**Comment by enoch85** [comment]
@HarveyKandola Hey! Any updates here?

**Comment by HarveyKandola** [comment]
It's part of the up-coming sprint that starts this week -- so you should expect it soon.

**Comment by enoch85** [comment]
It would also be nice if you coudl choose several sections at once to print specific sections at the same time. I hope that makes sense.

**Comment by enoch85** [comment]
What I would want is to put the print function in the section settings right about here:

![screenshot from 2019-02-11 13-48-40](https://user-images.githubusercontent.com/4511254/52564231-ed264a80-2e03-11e9-8419-eaa4b5021f11.png)

**Comment by enoch85** [comment]
Alternatively mark each section you want to print and only print the ones that are marked.

**Comment by HarveyKandola** [comment]
Done for next release.

**Comment by enoch85** [comment]
THANKS!

**Comment by enoch85** [comment]
I didn't find that option?

![image](https://user-images.githubusercontent.com/4511254/59791738-0cae1200-92d3-11e9-8b7f-bc79f214648b.png)

cc @HarveyKandola

**Comment by HarveyKandola** [comment]
It's at the document level menu -- Content -> Print.

Select your sections.
