### ISSUE TITLE
Unable to create user with name that includes cyrillic symbols

### ISSUE THREAD

**Issue by nkuznetsow** [documize/community#147]
When I try to create a user with name that includes cyrillic symbols I get next error in console: 

```
user.Add
execute user insert: Error 1366: Incorrect string value: '\xD0\xD0' for column 'initials' at row 1
```

Please, try to create a user with name "Иван Иванов" and you will get same error. 

Documize runs on Linux lineapp 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Documize version is Community Edition version 1.63.0
SQL variant MySQL
Database checks: SQL version 5.7.22

**Comment by sauls8t** [comment]
@nkuznetsow 

is this the user's full name? 'Иван Иванов'

**Comment by sauls8t** [comment]
@nkuznetsow found and fixed the issue for next release -- due end of this week.

Thanks for the report.

**Comment by sauls8t** [comment]
Fixed in latest release.
