### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by dampfhamm3r** [documize/community#149]
There's a problem while starting the up documize with SSL.
It doesn’t work if I have my CA-Cert, Issuing-Cert and my Server-Cert in one file, like this:

-----BEGIN CERTIFICATE-----
CA-CERT
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
ISSUING-CERT
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
SERVER-CERT
-----END CERTIFICATE-----
 
I get the error:
2018/05/07 14:45:16 http2: server: error reading preface from client ip.add.re.ss:53377: remote error: tls: unknown certificate authority

If I only put the Server-Cert in the .pem file, it works. But Firefox won't trust the site (Chrome/Safari = ok).

**Comment by HarveyKandola** [comment]
Conversation moved to support system.

**Comment by sauls8t** [comment]
Correct format/order for cert file:

-----BEGIN CERTIFICATE-----
SERVER-CERT
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
INTERMEDIATE-CERT
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
CA-CERT
-----END CERTIFICATE-----

**Comment by dampfhamm3r** [comment]
Exactly, that's the way it works.
Thx.
