### ISSUE TITLE
[Feature request] Store DB credentials during inital setup

### ISSUE THREAD

**Issue by dampfhamm3r** [documize/community#150]
It would be great if DB credentials could be stored in documize DB during inital setup.
So we wouldn't have to start documize this way:
./documize-enterprise-linux-amd64 -db='user:pass@tcp(localhost:3306)/documize' -dbtype=mariadb -salt=1234

If started as described above, credentials are visible for anyone on the server with "ps ax".

**Comment by dampfhamm3r** [comment]
I've done this - so I start documize with:
./documize-enterprise-linux-amd64 -port=$DOCUMIZEPORT -forcesslport=$DOCUMIZEFORCESSLPORT -cert=$DOCUMIZECERT -key=$DOCUMIZEKEY -db=$DOCUMIZEDB -dbtype=$DOCUMIZEDBTYPE -salt=$DOCUMIZESALT

This is working. But because the variables got resolved, the credentials are still visible in a "ps ax".
Or is there a fault on my side...?!

**Comment by sauls8t** [comment]
No, you are right. *nix will show ENV if you have the PID:

```ps e -ww -p <12345>```

A better way would be to fetch secrets from Vault:

https://www.vaultproject.io

Integration id doable assuming you can install Vault on your box.

**Comment by dampfhamm3r** [comment]
I'll have to take a look into this. Thx.
