### ISSUE TITLE
How to remove DRAFT label from document (make revision?)

### ISSUE THREAD

**Issue by nkuznetsow** [documize/community#151]
All of my documents contains DRAFT mark. 

![image](https://user-images.githubusercontent.com/8625715/39759346-e385e3bc-52eb-11e8-8cc7-f2ab36448ecf.png)

I already have finished work on this documents and want to remove this mark. Need I make the revision of the document? 

![image](https://user-images.githubusercontent.com/8625715/39759372-f3364ae0-52eb-11e8-971c-6441b50d7812.png)

I unable to found any way to remove the DRAFT label and any way to make a document revision. Please tell me whatch I need to press?

**Comment by sauls8t** [comment]
Document lifecycle is enterprise edition -- https://documize.com/downloads

How are you creating documents --- from import? template? empty?

**Comment by nkuznetsow** [comment]
I created the document from empty.

**Comment by sauls8t** [comment]
Did move between enterprise and community editions?

**Comment by sauls8t** [comment]
We've managed to track down your issue and will push out a new release.
