### ISSUE TITLE
User management broken at 1.64.1 and 1.66.1 (Maria DB 10.3.6)

### ISSUE THREAD

**Issue by sshaleniy** [documize/community#153]
When clicking at Users tab nothing happens on UI, at console error message: user.GetOrganizationUsers
 get users for org WvVMNXweARGgktaY: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`admin`, a.users as viewusers, a.analytics
                FROM user u, account a
                WHERE u.r' at line 2

Checked on both updated versions 1.64.1 and 1.66.1. Previous 1.64.0 and 1.66.0 works fine.

**Comment by sauls8t** [comment]
@sshaleniy thanks for the report -- please download 1.6x.2 series

**Comment by sshaleniy** [comment]
Thanks, love your fast reaction and fixing )
