### ISSUE TITLE
"Actions" tab is not visible if "Spaces" unchecked for him in user management

### ISSUE THREAD

**Issue by sshaleniy** [documize/community#154]
I'd like to block users from creating Spaces but if I un-check 'Spaces' checkbox at this user's settings, "Activity" tab also gone for him so user cannot complete Read request task ( a.k.a. 'Mark as complete').. Or maybe I'm doing something wrong?

**Comment by sauls8t** [comment]
If you are testing with your own account, then you should login again. 

Activity tab is visible for authenticated users. Actions like read requests will be marked as complete when:

1. User views document
2. User marks completed from Dashboard view

Please check.

**Comment by sshaleniy** [comment]
I'm using different accounts: as "Admin" I assign read request to "User" then logoff as "Admin" and login as "User" - no Actions tab for User. Tried to just view document as "User" -  request is still not fulfilled.

**Comment by sauls8t** [comment]
We have just made changes to provide more granular user permission management for Dashboard and Actions views.

New release dropping ASAP.
