### ISSUE TITLE
Cannot Grant "Create Document" Access On New Space 1.68.0-ee

### ISSUE THREAD

**Issue by samagnew** [documize/community#160]
Just was in the position of having to create a new space for a new working group. I can give every permission except "Create Document". I can neither remove this permission from me (the space creator) nor can I grant it to either a group or a user other than myself. All other permissions can be granted.

Obviously, this precludes the new space being used at all until this is fixed.

Sam

**Comment by sauls8t** [comment]
Just released v1.68.1 to resolve this issue -- download and try.

**Comment by samagnew** [comment]
Thanks, guys. That fixed it. Well, I can grant the permission anyway. I'll report back if users say it doesn't work but I'm sure it will.

Appreciate the timely fix.

Sam
