### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by DannySternol** [documize/community#163]
When installing dependencies I get the following error:
```shell
$ go get ./...
package github.com/documize/community/core/log: cannot find package "github.com/documize/community/core/log" in any of:
    /usr/lib/go-1.10/src/github.com/documize/community/core/log (from $GOROOT)
    /root/go/src/github.com/documize/community/core/log (from $GOPATH)
```

**Comment by HarveyKandola** [comment]
Is this after you have cloned this repo?

**Comment by DannySternol** [comment]
Sorry, my bad.
Read your instructions (https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16LOMucxwABhZF1/compiling-documize-from-source) again and now it works.
