### ISSUE TITLE
Error when exporting to PDF

### ISSUE THREAD

**Issue by jlounsbery** [documize/community#165]
I saw there was a closed issue that reported it as fixed, but this is happening on a new install for me today.
Documize Enterprise Free 
CentOS7
MariaDB 10.3.9

When Export to PDF is selected, it hangs for about a minute and then gives the following error:

SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data

**Comment by HarveyKandola** [comment]
Assuming your Documize instance is behind your firewall, please see the Conversion Service endpoint:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/general-options

We have a PDF conversion service update planned for release on Monday!

**Comment by jlounsbery** [comment]
I did not see that before now, thank you! We unfortunately haven't played around with docker much, but I will look into it. It would be nice to have the default working still.

**Comment by HarveyKandola** [comment]
Default will work if your Documize instance is accessible via internet!

**Comment by HarveyKandola** [comment]
Just HTTP/S ports.
