### ISSUE TITLE
Running port 443 with SSL cert, how do I capture 80 and forward?

### ISSUE THREAD

**Issue by bin4ryio** [documize/community#166]
Like title, should I run this behind a nginx server? or can I capture 2 port?

**Comment by HarveyKandola** [comment]
No need for nginx -- you can capture 80 and forward to 443:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/VzSL8cVZ4QAB2B4Y/environment-variables-and-command-lines-switches
