### ISSUE TITLE
[FR] Minimize content section

### ISSUE THREAD

**Issue by enoch85** [documize/community#170]
Imagine you have ALOT of Sections under one Space like here:

![screenshot from 2018-09-24 14-47-49](https://user-images.githubusercontent.com/4511254/45952937-d9bb4400-c008-11e8-9f2e-81938847f3d2.png)

...you would want to minimize them one by one so that not all are seen at once.

For example if you have it like this:
1.
   1.1
   1.2
   1.3
   1.4

You would want to minimize everything under 1 so that all the sub sections (1.x) aren't shown. This should also be the default value imho.

**Comment by enoch85** [comment]
No ETA on this?

**Comment by HarveyKandola** [comment]
We just implemented expand/collapse per section.

Due for next release.

**Comment by enoch85** [comment]
Awesome!

**Comment by enoch85** [comment]
(Or not working anyway) + the icons are not valid: 
![image](https://user-images.githubusercontent.com/4511254/59791612-d2447500-92d2-11e9-83e7-a349fbb21321.png)

**Comment by HarveyKandola** [comment]
It's in two places -- per section level menu option and top right corner of Table of Contents.

**Comment by enoch85** [comment]
Yes, I noticed that. But it doesn't minimize the content section itself (on the left hand side), only the content on the right hand side.

**Comment by HarveyKandola** [comment]
Correct -- by design.

At this stage, we only want to collapse the main view and not the document outline. That may change in future, so let's see.

**Comment by enoch85** [comment]
So what I mean is this.

You have 100 sections, with subsections. It gets messy pretty quickly...

What I would want is to be able to collapse the whole "section 4 segment", not just the text. I would also like it to apply for the left side menu.

![image](https://user-images.githubusercontent.com/4511254/60464038-ca2ef280-9c4d-11e9-92b1-d817166c803b.png)

Thanks for all your hard work!

**Comment by HarveyKandola** [comment]
Totally understand the issue.

But why do you have a document with 100 sections?! Would it not make sense to break it down into smaller documents (much like how we Developers strive for smaller code functions)?

**Comment by enoch85** [comment]
> But why do you have a document with 100 sections?!

Well, don't ask me. :) It's one of the users that decided to have it that way (they have their own space).

If possible it would be greatly appreciated.
