### ISSUE TITLE
[FR] Publish work from Teams to existing public Spaces / Sections

### ISSUE THREAD

**Issue by enoch85** [documize/community#172]
Let's say you want to work on something in a Team that shouldn't be published just yet. When the Team is done with all the editing of the specific sections, then make it possible to publish their work into existing sections/Spaces, a.k.a "merge" it in existing Spaces/sections.

Please ask if you don't know what I mean.

**Comment by sauls8t** [comment]
So you could create a space for the team, create your work and then move the documents to desired "public" space?

**Comment by enoch85** [comment]
Yeah, sort of. Let's say I'm working on a draft for a documentation, I would want to work on the draft "in secret" and when I'm done with my draft I'd like to publish it publicly and merge it with the already existing Documentation or "Space" in this case. 

Makes sense?

**Comment by HarveyKandola** [comment]
In which case you can just mark document as DRAFT in the space and control who can see it. 

When ready, change it to LIVE.
