### ISSUE TITLE
[FR] Make it possible to link to sections

### ISSUE THREAD

**Issue by enoch85** [documize/community#174]
It would be nice if you could link to sections by right clicking in the left "sidebar" and get a direct link to that section.

Here:

![screenshot from 2018-09-30 02 50 57](https://user-images.githubusercontent.com/4511254/46251732-af7be300-c45b-11e8-93a4-c352a331f422.png)

The workaround now is to inspect element and then try to figure out the link. Not that user friendly if you ask me :)

For referenence; you need to find the exact link like this `?currentPageId=W6yo9OPiqQz3_Mpy` when inspecting the element and then link to that to come to the right section.

**Comment by HarveyKandola** [comment]
Done for next release.
