### ISSUE TITLE
[FR] Add "Go to top" 

### ISSUE THREAD

**Issue by enoch85** [documize/community#175]
It would be nice if you could add a "go-to-top" icon so that you don't have to scroll to the top everytime you read a laaarge documentation and want to go back to the top.

An alternative would be to add the spaces menu in the bottom as well for easier navigation.

**Comment by evitalis** [comment]
Does the table of contents scroll with the actual page content? That could be another option here, then you can click the top section to go back to the top of the page.

**Comment by mcmatts** [comment]
Will be available in next release.

**Comment by enoch85** [comment]
This wasn't in the latest release 3.0.0

**Comment by HarveyKandola** [comment]
Look at the icon top right corner of table of contents:

![image](https://user-images.githubusercontent.com/971717/59792558-52b3a780-92cc-11e9-8af5-323dc31819c1.png)

**Comment by enoch85** [comment]
Aah, icon was missing on Firefox.
