### ISSUE TITLE
[FR] Make it possible to choose your own header colors or picutre

### ISSUE THREAD

**Issue by enoch85** [documize/community#176]
To make Documize more adaptable in an already existing color scheme, it would be nice if you were able to change background color of the "header" that is purple today. Adding your own background picture would be awesome as well!

**Comment by HarveyKandola** [comment]
Did you mean app scheme?

We are introducing per space "theming" as well as global "brand" color.

**Comment by rsaulo** [comment]
Hi, this is a nice feature, change colours and a LOGO.

**Comment by HarveyKandola** [comment]
Theme selector and custom logo upload has been implemented for v2 -- due for release any day now.

<img width="1541" alt="screenshot 2019-01-09 at 10 59 57" src="https://user-images.githubusercontent.com/971717/50898756-018fb580-1408-11e9-8c5b-88ef118cae89.png">
