### ISSUE TITLE
Migrate from Bower to Yarn+Webpack

### ISSUE THREAD

**Issue by nanopony** [documize/community#177]
First of all, I'd like to thank you guys for this amazing product! I totally love everything - starting from blazing fast speed, to the no-dependency deploy.

Do you have any plans or roadmap on upgrading frontend stack from bower? If you are okay with this idea I can try to help with the migration.

**Comment by HarveyKandola** [comment]
We just removed the "cosmetic" bower files in the upcoming sql-store branch (we have just added PostgreSQL database support).

Also removed package-lock and gone with Yarn.

In terms of Webpack, I believe Ember uses Babel?

**Comment by nanopony** [comment]
After a brief investigation ember-cli seems to be using own toolkit which likely to include Babel to transpile ES6. Maybe then webpack is not needed after all.

**Comment by HarveyKandola** [comment]
Given no bower references and the move to Yarn, we have a "decent" front-end stack!

At some point EmberJS will go mainstream with Typescript (I think it is possible now).
