### ISSUE TITLE
Can not connect to database

### ISSUE THREAD

**Issue by aitalinassim** [documize/community#181]
Hi

I have ubuntu server 18.04 VM

Create postgresql database
name: documize
user: documize
password (((((xxxx)))) (not real password)

When running 
sudo ./bin/documize-enterprise-linux-amd64 -port=5001 -db='documize:xxxx@tcp(localhost:5001)/documize' -dbtype=mysql -salt=1234567890acbdefg

I got the following:

unable to connect to database - database connection string format is 'username:password@tcp(host:3306)/database'
dial tcp 192.168.1.42:5432: connect: connection refused
goroutine 1 [running]:
github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc00001c910, 0xc000173c01, 0xc00005c690, 0x70, 0xd89bc0, 0xc00001c960)
	src/github.com/documize/community/edition/logging/logger.go:56 +0x168
github.com/documize/community/edition/boot.InitRuntime(0xc0001f8000, 0xc0000a1680, 0x7fff4ff6f772)
	src/github.com/documize/community/edition/boot/runtime.go:81 +0x337
main.main()
	src/github.com/documize/enterprise/edition/enterprise.go:64 +0x452

Extensions: registered 11 section types
Product: Enterprise Edition version 1.74.1 (build 181022154519)
Web Server: starting up
Web Server: binding non-SSL server on 5001
[negroni] listening on :5001
Processing Enterprise Edition license

and freeze, nothing happens.

Where can I find a tutorial how to install documize in ubuntu server, I can not find on the web,
otherwize, how to install on ubuntu server.

Thanks so much.

**Comment by aitalinassim** [comment]
OK,

when running:

sudo ./bin/documize-enterprise-linux-amd64 host=localhost port=5432 dbname=documize user=documize password=mypassword sslmode=disable

I got:

In order to run ./documize-enterprise-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of ./documize-enterprise-linux-amd64:
  -cert string
    	the cert.pem file used for https
  -db string
    	'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
    	specify the database provider: mysql|percona|mariadb|postgresql
  -forcesslport string
    	redirect given http port number to TLS
  -key string
    	the key.pem file used for https
  -log string
    	system being logged e.g. 'PRODUCTION' (default "Non-production")
  -offline string
    	set to '1' for OFFLINE mode
  -port string
    	http/https port number
  -salt string
    	the salt string used to encode JWT tokens, if not set a random value will be generated
please set DOCUMIZESALT or use -salt with this value: Xc8Eea939912cPya8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x92c56a]

goroutine 1 [running]:
github.com/documize/community/edition/boot.InitRuntime(0xc000202000, 0xc0000a3680, 0x0)
	src/github.com/documize/community/edition/boot/runtime.go:65 +0xaa
main.main()
	src/github.com/documize/enterprise/edition/enterprise.go:64 +0x452


____________________________________
Even if I change "localhost" to IP address of my server, or user from documize to admin; same result
I verified database, it is existing
db name: documize
user: documize
password: my password

Please help

**Comment by aitalinassim** [comment]
When running

sudo ./documize-enterprise-linux-amd64 -db='host=localhost port=5432 dbname=documize user=documize password=mypassword sslmode=disable'


I get:

In order to run ./documize-enterprise-linux-amd64 the following must be provided:
* setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: 'host=localhost port=5432 dbname=documize user=documize password=mypassword sslmode=disable' set by '-db'
* setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'

Usage of ./documize-enterprise-linux-amd64:
  -cert string
    	the cert.pem file used for https
  -db string
    	'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
  -dbtype string
    	specify the database provider: mysql|percona|mariadb|postgresql
  -forcesslport string
    	redirect given http port number to TLS
  -key string
    	the key.pem file used for https
  -log string
    	system being logged e.g. 'PRODUCTION' (default "Non-production")
  -offline string
    	set to '1' for OFFLINE mode
  -port string
    	http/https port number
  -salt string
    	the salt string used to encode JWT tokens, if not set a random value will be generated
please set DOCUMIZESALT or use -salt with this value: oDffcocU3hf019e9Q
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x92c56a]

goroutine 1 [running]:
github.com/documize/community/edition/boot.InitRuntime(0xc000218000, 0xc0000ab680, 0x0)
	src/github.com/documize/community/edition/boot/runtime.go:65 +0xaa
main.main()
	src/github.com/documize/enterprise/edition/enterprise.go:64 +0x452

**Comment by mcmatts** [comment]
Please check your switches!

sudo ./documize-enterprise-linux-amd64 -port=5001 -salt=tjhg75cn34dkfdy8cx3 -dbtype=postgresql -db='host=localhost port=5432 dbname=documize user=admin password=admin sslmode=disable'

Use the above as a template.

**Comment by aitalinassim** [comment]
Perfect,

Worked, on port 80

But web server stops when stop the ssh,
how to make it as a service to start on OS start and stays running ?

Regards.

**Comment by enoch85** [comment]
Here's the service:

```
wiki01:~# cat /etc/init.d/documize 
#!/sbin/openrc-run

name=$RC_SVCNAME
command="/bin/documize-community-linux-amd64"
command_user="root"
command_background="yes"
pidfile="/run/$RC_SVCNAME/$RC_SVCNAME.pid"
SOCKET=

depend() {
	need net
}

start_pre() {
	checkpath --directory --owner $command_user:$command_user --mode 0775 \
	/run/$RC_SVCNAME /var/log/$RC_SVCNAME
}

## Check if the socket exists and if it exists delete it.
	delete_socket() {
	if [[ -e $SOCKET ]]; then
	rm -f $SOCKET
	fi
}

start() {
	ebegin "Starting Documize"
	start-stop-daemon --start --background \
	--exec /bin/documize-community-linux-amd64 \
	--pidfile="$pidfile" \
	-- \
	-port=5001 \
	-db='documize:Passw0rd@tcp(localhost:3306)/documize' \
	-dbtype=mariadb \
	#-salt=a3e1ffpdAf681Vcfe
	eend $?
}

stop() {
	ebegin "Stopping Documize"
	start-stop-daemon --stop --pidfile "$pidfile"
	delete_socket
	pkill documize
	eend $?
}
```

**Comment by spectrumzhang** [comment]
marked
