### ISSUE TITLE
Panic when not passing correct parameters

### ISSUE THREAD

**Issue by dminGod** [documize/community#182]
Hi, 

- I just downloaded the app and tried to use it. 
- I know I am not using any parameters while starting the app which is wrong. Just raising this ticket just to bring light to the fact that the app shows a panic and runtime error in this situation. The error does not impact me, but, maybe you want to handle this exception so it doesn't crash. Cheers!

> user@hostname:/Desktop/apps$ chmod +x documize-enterprise-linux-amd64 
> user@hostname:/Desktop/apps$ ./documize-enterprise-linux-amd64 
> 
> In order to run ./documize-enterprise-linux-amd64 the following must be provided:
> * setting from environment variable 'DOCUMIZEDB' or flag '-db' or an application setting 'db', current value: '' set by '(default)'
> * setting from environment variable 'DOCUMIZEDBTYPE' or flag '-dbtype' or an application setting 'dbtype', current value: '' set by '(default)'
> 
> Usage of ./documize-enterprise-linux-amd64:
>   -cert string
>     	the cert.pem file used for https
>   -db string
>     	'database specific connection string for example "user:password@tcp(localhost:3306)/dbname"
>   -dbtype string
>     	specify the database provider: mysql|percona|mariadb|postgresql
>   -forcesslport string
>     	redirect given http port number to TLS
>   -key string
>     	the key.pem file used for https
>   -log string
>     	system being logged e.g. 'PRODUCTION' (default "Non-production")
>   -offline string
>     	set to '1' for OFFLINE mode
>   -port string
>     	http/https port number
>   -salt string
>     	the salt string used to encode JWT tokens, if not set a random value will be generated
> please set DOCUMIZESALT or use -salt with this value: 8dfMd92891d9cadfs
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x92c56a]
> 
> goroutine 1 [running]:
> github.com/documize/community/edition/boot.InitRuntime(0xc00020ab60, 0xc000206480, 0x0)
> 	src/github.com/documize/community/edition/boot/runtime.go:65 +0xaa
> main.main()
> 	src/github.com/documize/enterprise/edition/enterprise.go:64 +0x452

**This is the relevant section:**
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x92c56a]
> 
> goroutine 1 [running]:
> github.com/documize/community/edition/boot.InitRuntime(0xc00020ab60, 0xc000206480, 0x0)
> 	src/github.com/documize/community/edition/boot/runtime.go:65 +0xaa
> main.main()
> 	src/github.com/documize/enterprise/edition/enterprise.go:64 +0x452

**Comment by sauls8t** [comment]
Fixed for next release.
