### ISSUE TITLE
LDAP Authentication , Active Directory

### ISSUE THREAD

**Issue by Dogy007** [documize/community#184]
When setting up LDAP Authentication with a Active Directory host i had this issue.
I have validated with my own AD Server.

It states "Connection successful, found 0 users." 

This happens with different users (also Domain Admin) 

User filter = (|(objectCategory=person)(objectClass=user)(objectClass=inetOrgPerson))
Group filter = empty or cn=Documize

This only happens if the mail attribute is not set for the user in the Active Directory.

**Comment by sauls8t** [comment]
We need the LDAP/Mail attribute as it it mapped to Email within Documize.
