### ISSUE TITLE
Add possibility to sort contents

### ISSUE THREAD

**Issue by PHCCorso** [documize/community#187]
It'd be useful to add a sorting function when visualizing content and also on the search function. The sorting I'm suggesting is a sorting by creation and last edited dates, both ascending and descending.

Thanks for the attention!

**Comment by HarveyKandola** [comment]
Already on the hit-list!

We have a major update coming before the end of the year with revamped UX/UI.

**Comment by erhlee-bird** [comment]
Hey @HarveyKandola, can we reopen this?

This one's definitely an important issue to my team

**Comment by HarveyKandola** [comment]
Not sure we closed this issue in the first place.

**Comment by sauls8t** [comment]
sounds like the same sort filter for spaces and search
