### ISSUE TITLE
Use case without a db connection

### ISSUE THREAD

**Issue by lnxbil** [documize/community#188]
Hi all,

What it the use case of `documize` if the database connection fails in the beginning and the [application is not terminating at all](https://github.com/documize/community/blob/master/edition/boot/runtime.go#L67)?

I stumbled on this issue while creating a docker-compose setup in which `documize` is started before the database is ready resulting in a not working `documize` instance, which serves HTTP, but does not show anything. If I just restart or add a startup delay, `documize` works as expected.

I expect the application will terminate if the database is not reached, so that the external service handler (systemd, windows service or in my case docker) will automatically restart. I also expect this to happen if the database connection in terminated while `documize` is running and the db is restarted or temporarily not reachable.

Best,
Andreas

**Comment by lnxbil** [comment]
The line you mentioned will not be reached if the database connection is not established successfully, but I get your offline mode use case. What does it do besides not rendering any content of `documize`? I did not find any information about it besides this ticket on google :-D

**Comment by HarveyKandola** [comment]
We'll take a look and get back to you!

**Comment by HarveyKandola** [comment]
We've made a few tweaks for next release that resolve the no-database issue.

Process will terminate and explain why (including when using invalid dbtype switch).
