### ISSUE TITLE
[FR] Reverse proxy authentication

### ISSUE THREAD

**Issue by FlashSystems** [documize/community#191]
I'd like to use documize behind an apache reverse proxy. So far everything works very well but I've got one problem: In my setup the reverse proxy does the user authentication and passes the name of the authenticated user to the backend applications. My setup uses this technique to supply single sign-on for different web applications. I haven't found an option to make documize use the passed username instead of trying to authenticate the user.

Other services (like gitea for example) can be configured to use a supplied "X-Remote-User" header. If you could make this possible for documize as well, I'd really appreciate it. It's the last road block that keeps me from using documize.

**Comment by sauls8t** [comment]
Are the users in the Documize database?

Did you want to SSO with Documize?

**Comment by FlashSystems** [comment]
The SSO is done by the reverse proxy and the username is passed to documize. The passed login will not be the mail address but the SSO username. For the future the following workflow would be ideal:
If the passed username is known, it should be logged-in without further questions. If the username is not known, the user should be promted to fill in its information (name, mail, etc.). Documize should not handle or require any passwords. Everyting that reaches documize will already be authenticated by the reverse proxy.

**Comment by sauls8t** [comment]
Can the SSO process generate JWT?

**Comment by sauls8t** [comment]
Can the SSO process generate JWT?

**Comment by sauls8t** [comment]
@FlashSystems email our support team for follow-up and timeline
