### ISSUE TITLE
"Save as Template" form displays DELETE on button

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#192]
The "Save as Template" form that appears when trying to save a document as a template shows a "DELETE" button that seems confusing. Should that have text for "SAVE" instead?

![template_save_delete_button](https://user-images.githubusercontent.com/633268/51619896-42ef8d00-1eff-11e9-9fdc-2a304bfb0a5c.png)

From an instance running from master 2019-01-23.

**Comment by HarveyKandola** [comment]
Yup, resolved for point release due this weekend.
