### ISSUE TITLE
Can't upgrade to latest Documize

### ISSUE THREAD

**Issue by enoch85** [documize/community#197]
Hi!

Did you change anything in the upgrade process? I was using my script to update, and it doens't work anymore. It was working perfectly before.

```
#!/bin/bash

# Requires:
# - curl
# - wget
# - bash
# - A service for Documize (/etc/init.d/documize)

VERSION="$(curl -s https://api.github.com/repos/documize/community/releases | grep 'tag_name' | cut -d\" -f4 | head -1)"

service documize stop
sleep 2 # Wait for the service to stop completely
rm -f /bin/documize-community-linux-amd64
if wget https://github.com/documize/community/releases/download/$VERSION/documize-community-linux-amd64 -P /bin/
then
    chmod +x /bin/documize-community-linux-amd64
    echo "Rebooting in 5 seconds..."
    echo "5"
    sleep 1
    echo "4"
    sleep 1
    echo "3"
    sleep 1
    echo "2"
    sleep 1
    echo "1"
    sleep 1
    reboot
fi
```

What it does is basically:
1. Stops the service
2. Downloads the latest bin file
3. Reboots (and starts the service)

**Comment by HarveyKandola** [comment]
What is the issue exactly?

Any error conditions?

**Comment by enoch85** [comment]
@HarveyKandola To be honest I haven't investigated. Just wondered if you made any changes to the bin in general?

I'll see if I have time tomorrow to investigate it further.

Thanks!

**Comment by enoch85** [comment]
My bad, The MariaDB service had to be started at `sysinit` for it to work, so probably it wasn't started when documize started and failed due to that.
