### ISSUE TITLE
32bit arm build not generate binary

### ISSUE THREAD

**Issue by orsoone** [documize/community#198]
edition/community.go:45:24: constant 190205110701 overflows int

after i shorten rt.Product.Revision to 190205 build runs fine

**Comment by HarveyKandola** [comment]
Thanks for the report.

We can easily change the build number to a string no issue.

Which device/OS are you targeting for deployment?

**Comment by orsoone** [comment]
cubietruck , allwinner A20 2GB RAM, armbian latest with mainline kernel  sd boot + sata drive using go-lang package version 1.10
script for architecture autodfetection not work, even if add arch="arm" os="linux" it built linux darvin and windows versions , uncommenting if statements and using parameters behind elseif works

```
os=linux
arch=arm
echo "Compiling app..."
cd ..
#for arch in amd64 ; do
#    for os in darwin linux windows ; do
#        if [ "$os" == "windows" ] ; then
#            echo "Compiling documize-community-$os-$arch.exe"
#            env GOOS=$os GOARCH=$arch go build -gcflags="all=-trimpath=$GOPATH" -o bin/documize-community-$os-$arch.exe ./edition/community.go
#        else
            echo "Compiling documize-community-$os-$arch"
            env GOOS=$os GOARCH=$arch go build -gcflags="all=-trimpath=$GOPATH" -o bin/documize-community-$os-$arch ./edition/community.go
#        fi
#    done
#done
```

**Comment by HarveyKandola** [comment]
Thanks for the information. Looks like it is this:

https://archlinuxarm.org/platforms/armv7/allwinner/cubietruck

Did you get Documize to work on this board? Which database did you use?

**Comment by orsoone** [comment]
I am testing btrfs lzma + dedup with mysql server and memcached daemon, documize wortks great ,even the pdf export not work , its a special dependency in go ? or in linux system(like a wkhtmltopdf)?
and sorry for my bad english.
ps: btw cubieboard alongside with documize run suricata > barnyard2 > snorby without "any" problems :)

**Comment by HarveyKandola** [comment]
For PDF export and Word Import we have separate Docker container:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/customizing-documize?currentPageId=WS3-rjltKgABVdLe&source=conversion
