### ISSUE TITLE
Release notes are not visible

### ISSUE THREAD

**Issue by enoch85** [documize/community#199]
I thought it was just temporary, but it indeed seems like the Release Notes aren't public: https://docs.documize.com/s/betnq7venbkq5cjhoc0g/release-notes/ Been like that since a while back.

**Comment by enoch85** [comment]
Pic or it didn't happen:

![screenshot from 2019-02-10 18 52 43](https://user-images.githubusercontent.com/4511254/52537270-1643ce00-2d65-11e9-9ac0-1d0865c984b2.png)

**Comment by HarveyKandola** [comment]
Resolved.

**Comment by enoch85** [comment]
@HarveyKandola How did you resolve it? My docs suffer from the same issue:

**Logged in as admin:**
![screenshot from 2019-02-10 19 09 54](https://user-images.githubusercontent.com/4511254/52537478-bf8bc380-2d67-11e9-97c6-e839eaad0fbc.png)
**Not logged in:**
![screenshot from 2019-02-10 19 10 23](https://user-images.githubusercontent.com/4511254/52537477-bef32d00-2d67-11e9-86c5-ba12a44460b9.png)
**Permissions**
![screenshot from 2019-02-10 19 13 45](https://user-images.githubusercontent.com/4511254/52537516-05488c00-2d68-11e9-8e2c-31b08a36ba60.png)

**Comment by enoch85** [comment]
And yes: 

![screenshot from 2019-02-10 19 14 48](https://user-images.githubusercontent.com/4511254/52537530-28733b80-2d68-11e9-8bcf-5e8fd0ab048f.png)

**Comment by HarveyKandola** [comment]
Check category view permissions?

**Comment by enoch85** [comment]
That was it. Thanks! :100:
