### ISSUE TITLE
[FR] Tabular editor + CSV integration

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#202]
It would be really nice if we could import CSV files into the Tabular section as well as export as CSV files.

**Comment by sauls8t** [comment]
Is the CSV data going to be editable post-import?

Maybe a dedicated CSV section type for uploading, displaying and exporting data would be better?

**Comment by erhlee-bird** [comment]
We definitely have a few use cases where we would want to edit the CSV data post-import.

But as a starting point, we could just do editing ourselves on the CSV files pre-import.

**Comment by HarveyKandola** [comment]
See #208

**Comment by HarveyKandola** [comment]
Expect resolution next week with v2.1.0 -- we have implemented an all-new Tabular section type that should support CSV importing as well.
