### ISSUE TITLE
add tenants in CE edition?

### ISSUE THREAD

**Issue by ggazulla** [documize/community#204]
I'd like to know if is it possible add tenants in CE Edition, and if is it, how I can do it?

Thanks

**Comment by HarveyKandola** [comment]
So this is really an enterprise edition setting but see the overview here:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO4Rm_MXigAB6sLP/how-documize-supports-multiple-tenants

**Comment by ggazulla** [comment]
Hello, I was trying Enterprise edition too, but no way to make this setting... I revised the api/documentation twice, if you can bright some light in this question i'll be grateful,

Thanks

**Comment by sauls8t** [comment]
Contact us via email and we will get someone to help you out.

**Comment by ggazulla** [comment]
Thanks for your quickly reply, which email should I contact?
Thanks

**Comment by sauls8t** [comment]
support atdocumize.com
