### ISSUE TITLE
[FR] PDF display section

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#207]
A really nice-to-have section would be a PDF rendering section. Possibly powered by something like https://github.com/mozilla/pdf.js.

The two workflows that would be nice to have would be as follows.
- Create a PDF section, drag and drop a PDF file that then gets rendered and is scrollable page to page.
- Create a PDF section, use a UI similar to "Insert Link" to find attachments either within the wiki or from a network source.

A perfect example is in the way that GitHub does PDF blob rendering. Multiple pages get rendered with the page breaks clearly illustrated.
- https://github.com/euske/pdfminer/blob/master/samples/nonfree/dmca.pdf

This would enable us to transition some existing files as well as support a workflow for making powerpoint presentations displayable inline as well.

**Comment by HarveyKandola** [comment]
Makes perfect sense.

We would add a PDF Viewer section type like you say.

We (internally) just need to consider #171 as part of the design.

**Comment by HarveyKandola** [comment]
Done for next release (v2.4.0)
