### ISSUE TITLE
Add Tabulator in Insert Section

### ISSUE THREAD

**Issue by harpalpatiala** [documize/community#208]
Any future plan on adding http://tabulator.info/ in Insert section.
It would be great to have such tables within Documize documents.

**Comment by HarveyKandola** [comment]
We're looking into https://bossanova.uk/jexcel at the moment and will take a look at Tabulator as well.

We need a method for people to add and format cells to suite their needs.

**Comment by HarveyKandola** [comment]
We have introduced a more rich tabular section type that also supports CSV data import.
