### ISSUE TITLE
Cant upload custom logo

### ISSUE THREAD

**Issue by backba** [documize/community#209]
When trying to upload a custom logo everything looks like it should, got no errors. But the logo does not change, just have the builtin logo as before. Have verified that the logo is uploaded in the database (table dmz_org) I am using MariaDB as databse.

Version: Enterprise Edition v2.0.4 (build 190211192501)

**Comment by HarveyKandola** [comment]
Can you use and try v2.0.6 in the first instance?

**Comment by backba** [comment]
Just tried the 2.0.6, but with same result..

Is there any way of extending the logging in the application?

**Comment by erhlee-bird** [comment]
Can confirm the same issue

**Comment by HarveyKandola** [comment]
Can you confirm file type and size?

**Comment by backba** [comment]
I have tried some different sizes, but the last one I tried was 64 x 64 pixels and image size is 4kb.

**Comment by HarveyKandola** [comment]
@backba do you see anything in server console / syslog?

@erhlee-bird which DB?

**Comment by backba** [comment]
I cant see anything in the logs, is there anyway to extend the logging?

**Comment by HarveyKandola** [comment]
@backba in your browser, can you check the developer console for any messages related to the issue?

Also can you test again our cloud environment?

https://www.documize.com/cloud-signup/

**Comment by backba** [comment]
Just tried your cloud, and it worked without any problems.

**Comment by sauls8t** [comment]
@backba that might suggest a MariaDB related issue.

Hit supportatdocumizedotcom and we will set up a call to resolve.

**Comment by backba** [comment]
Cool! Will do that :)

**Comment by HarveyKandola** [comment]
@erhlee-bird ensure that ```dmz_org.c_domain``` reflects any subdomain you are using.

Example ```dmz_org.c_domain``` should be ```docs``` if you access Documize via ```docs.example.org```.

Next release will detect and fall back automatically for this scenario.

**Comment by erhlee-bird** [comment]
Sweet, that fixed it for me. Thanks for the quick fix
