### ISSUE TITLE
LDAP/Active Directory authentication

### ISSUE THREAD

**Issue by bserrao** [documize/community#210]
Hello, 

When setting up the Active Directory or LDAP it's possible to use the login fields as authentication to query the AD? I don't have an admin user to the AD but i would like to use the inserted username/email as BIND DN and the Password as Bind Password in order to authenticate.
Is this possible in documize? I would put the username/password variables in BIND DN and BIND Password, like $1user and $2password for instance...

I've had this kind of setup on Xwiki ...

Thanks,

**Comment by HarveyKandola** [comment]
You mean bind with the logged in user? If so, not possible at the moment.

If you need additional control over AD/LDAP, try this:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WNEp8tWJ9AABRnhj/authenticating-with-redhat-keycloak

**Comment by bserrao** [comment]
Yep, i mean bind with the user trying to login. 
Ok, thanks. I'll have to find another way...
