### ISSUE TITLE
Clipboard bug in Tabular Paste content twice

### ISSUE THREAD

**Issue by harpalpatiala** [documize/community#211]
Pasting  from Clipboard using CTRL+V Paste content twice in a Cell.
Look screenshot below:

![image](https://user-images.githubusercontent.com/27708953/53365925-68414200-3968-11e9-9c81-b319d84fe5b6.png)

Running: Community Edition v2.0.6 (build 190223170338)
Server: Windows Server
DB: MariaDB
Client: Google Chrome on Windows 10

**Comment by HarveyKandola** [comment]
Expect resolution next week with v2.1.0 -- we have implemented an all-new Tabular section type that should support CSV importing as well.
