### ISSUE TITLE
LDAP user access API

### ISSUE THREAD

**Issue by javier-izquierdo-visualfy** [documize/community#212]
We have LDAP authentication configured, and we want to access via API but LDAP users do not have permissions, Is there any possibility to choose which users can or cannot accces the API?

**Comment by mcmatts** [comment]
You have documize connected to LDAP for user sync and auth?

What API do you want to lock-down?

**Comment by javier-izquierdo-visualfy** [comment]
yes, we have documize connected to LDAP, but no user of ldap has connection by api, sorry for my bad english

**Comment by mcmatts** [comment]
sounds like users cannot authenticate with LDAP server through Documize.

right?

**Comment by javier-izquierdo-visualfy** [comment]
Hello again!

My users can connect via Web to Documize but they are not able to authenticate using the API.
Here is an example: 

curl -X POST \
  http://docs.visualfy.com/api/auth/login \
  -H 'Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXX \
  -H 'Cache-Control: no-cache'

Thanks in advance

**Comment by HarveyKandola** [comment]
We think we understand what you saying.

If you want to programatically authenticate with LDAP via our API then the endpoint is ```api/public/authenticate/ldap```.

If you need to discuss anything sensitive please email supportatdocumizedotcom
