### ISSUE TITLE
PlantUML charset utf-8

### ISSUE THREAD

**Issue by javier-izquierdo-visualfy** [documize/community#213]
We are using PlantUML to make diagrams but, we would need to have compatibility with utf-8 to be able to show accents and characters like the ñ, any ideas?

**Comment by mcmatts** [comment]
UTF-8 should work -- we'll verify and issue update if required.

**Comment by HarveyKandola** [comment]
@javier-izquierdo-visualfy can you provide a screenshot of the problem as we cannot seem to replicate it.

**Comment by javier-izquierdo-visualfy** [comment]
@HarveyKandola 
participant "I have á reallylong name" as L #99FF99
![image](https://user-images.githubusercontent.com/46961459/53491847-aee18a00-3a97-11e9-9b62-fcacdae26917.png)

**Comment by HarveyKandola** [comment]
Thanks.

This is what you should expect:

![image](https://user-images.githubusercontent.com/971717/53492135-00861680-3a90-11e9-8aba-e8af921a0f53.png)

We think the issue is related to the default character set on the host running Documize.

For next release (due next week), we have set the default to be explicit UTF-8.

**Comment by javier-izquierdo-visualfy** [comment]
hi again @HarveyKandola, before update to version 2.1.1 the error not resolve...

You are running Community Edition v2.1.1 (build 190304203624)
![image](https://user-images.githubusercontent.com/46961459/54022732-762a6a80-4193-11e9-9627-7c0594b3bb7c.png)

**Comment by HarveyKandola** [comment]
So we just updated the conversion service to 2.3.0 and it should work.

If you local install (Settings -> General) points to api.documize.com then please test again.
