### ISSUE TITLE
[Bug Report] Click to search tag on document

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#214]
I have a document that I've tagged with "guide".

![tagged-item](https://user-images.githubusercontent.com/633268/53514094-e7339900-3a94-11e9-9223-40966381250d.png)

Clicking on the guide tag takes me to the search page with seemingly correct parameter arguments, but doesn't perform the search.

![search-page-no-results](https://user-images.githubusercontent.com/633268/53514192-26fa8080-3a95-11e9-91f6-c6d068826a84.png)

This is what I would expect to have happened.

![proper-search](https://user-images.githubusercontent.com/633268/53514236-48f40300-3a95-11e9-8386-e21414e59790.png)

**Comment by sauls8t** [comment]
Resolved for next release v2.1.0

/cc @HarveyKandola
