### ISSUE TITLE
[FR] Recently updated documents

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#215]
Would be really nice to have some spot in the UI to see a list of documents that have been recently updated.

Specifically a view for users without more fine-grained analytics permissions.

**Comment by HarveyKandola** [comment]
So the activity view is being re-worked to provide filters in sidebar to show activity by type.

This request fits that perfectly.

**Comment by mcmatts** [comment]
Just added recent add/update to the space filters just above the category filters.

This is a space level filter and not present on the activity dashboard. This is the only way round having to not to give analytics/actvitity permissions.

**Comment by HarveyKandola** [comment]
@mcmatts perfect -- I just saw the change.

@erhlee-bird expect two new space level filters for all users to see latest content additions and updates.
