### ISSUE TITLE
[Bug Report] Blockquote in markdown section

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#217]
Blockquotes don't seem to be rendering in the markdown section.
This is on a cloud instance running v2.0.6

![sketch](https://user-images.githubusercontent.com/633268/53613828-58627180-3ba5-11e9-9035-6c3fbf165f20.png)

![sketch](https://user-images.githubusercontent.com/633268/53613849-6d3f0500-3ba5-11e9-9348-4b293180dcfb.png)

**Comment by HarveyKandola** [comment]
Implemented for next release (v2.1.0 due next week).
