### ISSUE TITLE
[FR] Compact mode

### ISSUE THREAD

**Issue by Req** [documize/community#218]
If there are more than 10 spaces and/or contents per space (especially if there are hundreds), it is difficult to glance over the listing (I find myself often not knowing what I am searching for before I find it). Adding a compact mode view, where whitespace is minimized (like the administration sidebar) to all or some of these would help greatly in using Documize:

- user setting
- documize setting
- space setting

Perhaps something like this - but even more compact would be better 
![image](https://user-images.githubusercontent.com/635732/53744968-cc9f5c80-3ea6-11e9-9c72-03e152b625fb.png)

**Comment by Req** [comment]
As a post-thought, it would be even better if the description field and label(s) were completely hidden in com,pact mode.

**Comment by HarveyKandola** [comment]
@Req makes sense.

Just to clarify:

1. Compact view for spaces list
2. Compact view for contents list when viewing a single space

Did we miss anything from your requirements? 

You mentioned admin sidebar -- as an example of compactness or to hide that as well?

**Comment by Req** [comment]
@HarveyKandola Thank you, yes those two are exactly what I mean! And exactly as you said I meant that the admin sidebar is an example of compactness.

**Comment by mcmatts** [comment]
Completed for release 2.2.0 (due next week)
