### ISSUE TITLE
[FR] Space content listing when viewing content item

### ISSUE THREAD

**Issue by Req** [documize/community#219]
I often open multiple contents in quick succession and it would be very nice to view the content listing from inside a content (sorry to say this, but yeah similarly to what that certain Atlassian product does with its hierarchy tree). It is very useful when browsing through very large amounts of content.

Optimally this could be toggled based on Documize setting, space setting and user preference.

I was imagining something like this space I added (I'm no UX wizard mind you and an integration to the existing .master-sidebar might be more UX-friendly!): 
![image](https://user-images.githubusercontent.com/635732/53746062-11c48e00-3ea9-11e9-8aed-ef2c96c604cb.png)

**Comment by HarveyKandola** [comment]
That would/could work in a couple of way:

1. Space content jump list available from within the content being viewed is dead useful.
2. Recently Viewed content list serves a similar purpose but goes across all spaces.

We're also working on 'related content' section at the bottom of the content view.

Tasteful UI should remove the need to toggle this functionality.

Thoughts welcome.

**Comment by Req** [comment]
@HarveyKandola If I understood, 1. would be like I tried to display in my example image - I'm trying to jump quickly from content to content within a space glancing over each of them - preferably so that I don't have to scroll up or press the backspace to return to the space.

As for related content & recently viewed - I don't think either servers my purpose and I don't see them valuable to myself - perhaps to others! I will give my two use cases for this feature to you:

Use case A: Documize used to document ~50 projects (spaces) and each project has 10 - 50 content pages. A user needs to find "X" in a project. It's likely they have never heard of the project or of "X". This "X" might be hidden in one of the space pages and the user has no idea where, so they need to quickly scan each of the content pages.

Use case B: Documize used to document ~50 projects (spaces) and each project has 10 - 50 content pages. A user must check that each of them have certain 5 content pages each with a specific name and with a specific content. In 90% of the spaces they are OK, everything needs to be checked and sometimes they are named incorrectly, so the user must scan through the project space listing quickly.

**Comment by mcmatts** [comment]
Completed. Will be part of next release.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/26042987/58333894-4ad02700-7e36-11e9-9b16-8e9d564c1d6c.png">
