### ISSUE TITLE
[Documentation] How to add a new Section type 

### ISSUE THREAD

**Issue by Req** [documize/community#220]
I really want to add at least one new Section type to Documize, but I have no idea where to start. 

I remember seeing somewhere an indication that the section list might be extendable, but can't find any pointer as to how. I am willing to learn (some) golang / ember if that is what it takes and I am willing to publish the type as a plugin or, if I must, even a core feature (although a plugin would be best for obvious reasons).

Is it possible that someone creates a documentation section or a blog post or something?

**Comment by HarveyKandola** [comment]
This should help you:

https://docs.documize.com/s/leFaXwlU/compiling-and-contributions/d/bhv3mb0v4p00jjof28i0/building-data-integrations
