### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by koshia** [documize/community#221]
Documize Version 2.1.1 Community, New Install
MariaDB Version 10.3.13
Debian 9.8, 64bit

---------------------------------------------------
LDAP Authentication results in "Invalid Credentials".
---------------------------------------------------

After configuring the LDAP settings and testing - it can connect to AD. It found users and synchronized just fine. After synchronization, I tried logging in with a test account, but all login attempt fails with the same "Invalid Credentials" error:

1. domain\user (this threw an error that there was an illegal character - which I'm guessing is due to the backslash) - did not work
2. emailaddress@domain.tld - results in invalid credentials
3. username - results in invalid credentials

I'm unsure where the errors are streamed to, to debug this problem.  I did look in /var/log/syslog and did not see any authentication/related LDAP problems.

Please advise.

Thanks!

**Comment by mcmatts** [comment]
Did you *activate* the LDAP authentication provider?

**Comment by koshia** [comment]
> Did you _activate_ the LDAP authentication provider?

I did. It actually locked me out of the application since i had LDAP as the active auth method.  Luckily, the browser saved an SSO link that allowed me to get back in and then changed back to local auth method instead. 

Which brings up another potential issue - the SSO link being non-expiry?  Or perhaps, there's an expiry to the cookie? If it's functioning the way it's supposed to, I won't create another issue to track.
https://<serverip>:<port>/auth/sso/<some random encrypted string>

**Comment by mcmatts** [comment]
See this for resetting the auth provider:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/bh2upsa1b54as00dsd10/authentication-provider-troubleshooting

Best to email supportatdocumizedotcom for help as one of the team we ask for diagnostic information from your installation.
