### ISSUE TITLE
Insert attachment as an image link

### ISSUE THREAD

**Issue by carddamom** [documize/community#222]
Is it possible to upload a attachment that is a image file and then in the editor create a image link to it? Instead of inserting the contents of a image as a data-uri?

**Comment by HarveyKandola** [comment]
Upload as attachment.

Then insert link to image in any Rich Text or Markdown section type.

**Comment by carddamom** [comment]
Yes but in the rich text editor, when I select "Insert/Edit" image the image that I've uploaded as a attachment does not show as a available image, for example in a combo box ou a autocomplete input field

**Comment by mcmatts** [comment]
Can you send a screenshot?

**Comment by erhlee-bird** [comment]
@mcmatts managed to repro

Step 1: Upload attachment and hit Insert Link in the Rich Text Editor section

![step-1](https://user-images.githubusercontent.com/633268/54532677-c3aa9280-495e-11e9-9300-5b9e58b3edb9.png)

Result: Appears as link, not an image
![step-2](https://user-images.githubusercontent.com/633268/54532721-dc1aad00-495e-11e9-83bc-80d3996c6720.png)

Step 2: Upload image in Rich Text Editor UI
![step-3](https://user-images.githubusercontent.com/633268/54532756-f3f23100-495e-11e9-8398-24d39b09df18.png)

Result: Image appears as expected
![step-4](https://user-images.githubusercontent.com/633268/54532766-fb193f00-495e-11e9-9ec4-4231d0007632.png)

**Comment by HarveyKandola** [comment]
Got it!

So what you need is for image attachments to be inserted as pictures and not links?

**Comment by sauls8t** [comment]
Alternative is to paste the image directly into the editor.
