### ISSUE TITLE
[Bug Report] Images uploaded in rich text editor not in attachment list

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#223]
Don't have a computer to test this for a while, but I believe that an image uploaded in the rich text editor don't show up in the attachments list.

**Comment by erhlee-bird** [comment]
Reminded by #222

**Comment by mcmatts** [comment]
It's by design for now.

Section level attachments are coming -- should be what you need?

**Comment by erhlee-bird** [comment]
Gotcha, if they could appear in the eventual section level attachment list, that would be ideal.

**Comment by HarveyKandola** [comment]
That's the plan -- section level list of attachments.

**Comment by HarveyKandola** [comment]
Section level attachments are done.
