### ISSUE TITLE
Login to documize is pointed to localhost

### ISSUE THREAD

**Issue by famasya** [documize/community#224]
How to set proper documize installation domain? 

Any email I sent, the "Login to Documize" button is always pointed to localhost. Example:

```
http://localhost:5001/s/bhlpkdjdk2hse5qk5bkg/bpjs-vclaim
```

**Comment by HarveyKandola** [comment]
Suspect this is an issue with your server's hostname setup (e.g. docs.example.org).

Documize uses whatever URL was used to access the web app.

**Comment by Nexoz** [comment]
Hi !

We have exactly the same problem, button "Login to Documize" points to 127.0.0.1:3000.

We're using a nginx reverse-proxy with this simple conf :
![1CEB4A8](https://user-images.githubusercontent.com/16245319/55733426-1cc98b80-5a1e-11e9-81bf-1bea3e0ead2d.PNG)

Thank you for your time.

**Comment by HarveyKandola** [comment]
Ah, so the proxy support seems to be the issue here.

We'll look into this and resolve...

**Comment by HarveyKandola** [comment]
So, I can't tell clearly from your screenshot how you want it to work, but you might want to try the following.

If you want to access Documize as "https://docs.atlas" and "atlas" is the server name, then set the following database field to "atlas"

```
dmz_org.c_domain
```

Try it and let us know.

**Comment by badmark** [comment]
Having same issues. When adding new users it emails them with a link to the internal server, not the Actual domain, using NGINX as a reverse proxy.

**Comment by HarveyKandola** [comment]
Folks, we're looking into this at the moment.

**Comment by HarveyKandola** [comment]
@famasya are you also using a reverse proxy?

@Nexoz @badmark can you try to use $http_host instead of $host?

```proxy_set_header Host $http_host;```

**Comment by Nexoz** [comment]
Putting $http_host in nginx config worked us.

Thanks for the quick fix.

**Comment by HarveyKandola** [comment]
@Nexoz 

Thanks for the update.

We still have some edge cases with reverse proxy deployments and next release will address those.

**Comment by famasya** [comment]
> @famasya are you also using a reverse proxy?
> 
> @Nexoz @badmark can you try to use $http_host instead of $host? Send your nginx.conf files to supportATdocumizeDOTcom.
> 
> `proxy_set_header Host $http_host;`

Yes, I am under reverse proxy too. Thank you for the quick fix. Will try it later.

**Comment by famasya** [comment]
Since I use apache2, following config works for me
```
ProxyPreserveHost on
```

**Comment by HarveyKandola** [comment]
Documented:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide

**Comment by HarveyKandola** [comment]
Documented:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide
