### ISSUE TITLE
search with advance query

### ISSUE THREAD

**Issue by kyhuynhduc** [documize/community#230]
Community Edition v2.2.0 (build 190313174432)
DB: Postgres
--
is advance query available on community version? 
when i use [!] and [&] in query, i expect to exclude some tag on document on search result. 
<img width="1280" alt="Screen Shot 2019-03-19 at 1 41 45 PM" src="https://user-images.githubusercontent.com/36893030/54585539-e7e49d00-4a4c-11e9-9279-3e4c284beaca.png">

<img width="1280" alt="Screen Shot 2019-03-19 at 1 47 12 PM" src="https://user-images.githubusercontent.com/36893030/54585749-8e30a280-4a4d-11e9-9314-988d8a593959.png">

**Comment by HarveyKandola** [comment]
Does the query work if you de-select the Tag option in the sidebar?

**Comment by kyhuynhduc** [comment]
> Does the query work if you de-select the Tag option in the sidebar?
it was i work on documize for querry.

![Mar-21-2019 09-20-49](https://user-images.githubusercontent.com/36893030/54730287-affb6800-4bba-11e9-8a66-ba1c9f47669e.gif)

**Comment by mcmatts** [comment]
Can't see the image clear enough to know if thge query worked.

Did it work?

**Comment by kyhuynhduc** [comment]
> Can't see the image clear enough to know if thge query worked.
> 
> Did it work?

no it didn't 
re-up the gif FIY.
![Mar-21-2019 18-37-08](https://user-images.githubusercontent.com/36893030/54749873-794c3e80-4c08-11e9-8760-886d693c85ea.gif)

**Comment by HarveyKandola** [comment]
Better search now supported when self-hosting and using Microsoft SQL Server 2016+.
