### ISSUE TITLE
Out of memory while doing backup

### ISSUE THREAD

**Issue by david-quijano** [documize/community#231]
Hi,
I'm doing a backup of my data and the server dies with the following:
[backup.log](https://github.com/documize/community/files/2986130/backup.log)
I can see it runs out of memory.

It's a 1GB RAM server and it runs perfectly.
Before I try to do a backup I have around 350MB RAM free.
I'm using PostgreSQL as DB and I can do a pg_dump without any issues.
What is the backup tool doing to require so much memory?
Is it ok to use pg_dump and pg_restore for doing backups?
Do I need to backup any other files/configs?

**Comment by HarveyKandola** [comment]
You can use pg_dump as all data is held inside the SQL database.

We know the backup process needs to be more efficient!
