### ISSUE TITLE
Export Content in Page

### ISSUE THREAD

**Issue by Luisfermp18** [documize/community#232]
Hi,

I'm looking for help to answer the following question: ¿Is there any possibility to export the content of a specific page as PDF/TXT/WORD?

![Captura de pantalla 2019-03-20 a las 17 21 27](https://user-images.githubusercontent.com/5788484/54701128-a92a1200-4b34-11e9-9036-4fe04ae009de.png)

**Comment by mcmatts** [comment]
Per export section is due soon.

See #146

**Comment by Luisfermp18** [comment]
Thx a lot! 

I will close this issue, because it was duplicated! :D
