### ISSUE TITLE
[Bug Report] Attachment URLs are not friendly to embed/object

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#236]
In trying to investigate a way to embed pdfs and other file types as viewable content in a section rather than just a link, I experimented with the embed and object HTML5 tags in a markdown section which works to an extent.

In a Markdown section I have the following.

```
XXX: This displays really nicely in Edge but neither Chrome nor Firefox.
<object data="https://documize.internal/api/public/attachment/...?token=..."
        type="application/pdf" 
        width="100%" 
        height="800"> 
</object>
```

This displays very nicely in Microsoft Edge on Windows 10, but neither Firefox nor Google Chrome seem to be able to load the pdf appropriately when it is an attachment.

Google Chrome on Windows 10:
![207-chrome](https://user-images.githubusercontent.com/633268/55585897-bbd84580-56f5-11e9-84c0-c464bcabc030.png)

Microsoft Edge on Windows 10:
![207-edge](https://user-images.githubusercontent.com/633268/55585951-d5798d00-56f5-11e9-8629-eaec40ba1ea3.png)

Related Issues:
- https://github.com/documize/community/issues/207
- https://github.com/documize/community/issues/222

I suspect this issue may have something to do with the following issue (content/attachment links) as looking at the DOM for Chrome, Chrome is rerouting the PDF load to an extension which may not be granted the same permissions as the current page I am viewing.
- https://github.com/documize/community/issues/233

If this could be fixed, it would be huge for helping us transfer some initial documents and alleviate some of the early growing pains.

**Comment by erhlee-bird** [comment]
Also confirmed that it works in Safari

**Comment by sauls8t** [comment]
We'll have to escalate #207 for PDF rendering section.
