### ISSUE TITLE
[Bug Report] Thai language search fails.

### ISSUE THREAD

**Issue by asisunyapoth** [documize/community#237]
Search query seems not to be working with Thai language.

When I try searching using Thai keyword "ข้อมูล", documize returns "nothing found".

![Documize - Search Page](https://user-images.githubusercontent.com/1991275/55794841-8a45ec80-5af0-11e9-93e7-467c2a276825.GIF)

A page with such a keyword does exist, as shown below.

![Documize - Content Page](https://user-images.githubusercontent.com/1991275/55795040-0b04e880-5af1-11e9-8275-288bd3dbb9b8.GIF)

Any Thai keywords have the same problem. English keywords work fine.

This happens with the Enterprise Cloud edition, as well as the Community On Premise edition.

**Comment by HarveyKandola** [comment]
Thai language is now supported when self-hosting and using Microsoft SQL Server 2016+.
