### ISSUE TITLE
Link to postman collection is broken in docs

### ISSUE THREAD

**Issue by afreepenguin** [documize/community#239]
https://docs.documize.com/s/WtXNJ7dMOwABe2UK/api/d/WtWbRbdMOwABe2SK/authentication

https://docs.documize.com/api/public/attachments/8SwAtYoB/Wt9CaXcHWQABMuQM

**Comment by HarveyKandola** [comment]
Expect a resolution on Saturday when we deploy v2.3.1.

**Comment by afreepenguin** [comment]
Got all connected, no rush! Thanks.
