### ISSUE TITLE
Draft documents published

### ISSUE THREAD

**Issue by backba** [documize/community#242]
We are using Documize and it feels really promising, just started the big work to get all our documents into Documize. 

Realized one thing though, if I have 2 versions of a document and only one of them are published and the other one is in Draft mode it will also be visible (if you change version). The document are published and visible for everyone (No need to login).

We are using the latest version: 2.3.0

**Comment by HarveyKandola** [comment]
Sounds like a loophole which we will fix shortly.

**Comment by HarveyKandola** [comment]
Fixed and due in next point release (this week).

**Comment by backba** [comment]
Just updated and the bug is crushed! :)
