### ISSUE TITLE
How to change max upload files

### ISSUE THREAD

**Issue by javier-izquierdo-visualfy** [documize/community#244]
Hi, i need upload file with 80M to documize how to change max upload file limit?.

**Comment by HarveyKandola** [comment]
Assumptions: you are self-hosting Documize and probably using MySQL database provider.

If so, see this:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V2KuM8ICcQABagM5/mysql-specific-database-tuning
