### ISSUE TITLE
auto logged out after opening a space in a separate tab

### ISSUE THREAD

**Issue by eddie1030** [documize/community#246]
Hi

I looked for an answer in the existing issues, but can't seem to find it yet. If I overlooked, please excuse me.

I'm hosting the Documize binary in a LXC container on a Debian 9 host. I use pgsql 9.6 for the database, both for content and user accounts.

*It works great apart from one issue:* when I login as any user and try to open a space in a separate tab (right click , open in separate tap , on firefox 60), i get logged out in both the original tab and the new one.

I use haproxy as a loadbalancer, but since I only run one instance at this moment, it should act as a transparent proxy i guess.

It's pretty obvious I run into this problem with Documize only, so I wonder, did I miss something during configuration, or is this really a bug?

Many thanks in advance for feedback

Best 
ed

**Comment by HarveyKandola** [comment]
Thanks for the report @eddie1030 -- could be an issue with Documize with haproxy -- drop supportATdocumizeDOTcom and we can deep dive the issue.
