### ISSUE TITLE
[Bug Report] Login icon is subtle

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#247]
As I introduce Documize to more users in my organization, I notice that a very common bit of feedback is that the login icon is not super apparent leading to some confusion when they cannot access spaces/documents that they expect to.

Additionally, passing a link to a user that is not logged in leads them to the "Oops! That page couldn't be found." page. Perhaps instead of only redirecting them to the home page, an additional workflow could be added to direct them to login.

**Comment by sauls8t** [comment]
@erhlee-bird 

Best to label this as a "bug".

@HarveyKandola 

Two things:

1. Up-coming UX/UI should label Login (top right?)
2. Change 404 to login?

**Comment by HarveyKandola** [comment]
Done for next release.
