### ISSUE TITLE
export pdf fail

### ISSUE THREAD

**Issue by kt1024** [documize/community#251]
version: Enterprise Edition v2.4.0  (free version, just activated)
db: postgresql
OS: debian 9

select 'export pdf' , in about a minute, page goes to:
<code>{Error: 'Internal server error'}</code>

and terminal is full of logs like this:
<code>
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc0004a54a0, 0x7fe751fc9130, 0xc00000e008, 0xc00012a700)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xec
github.com/documize/community/vendor/github.com/gorilla/handlers.ProxyHeaders.func1(0x7fe751fc9130, 0xc00000e008, 0xc00012a700)
	src/github.com/documize/community/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x10d
net/http.HandlerFunc.ServeHTTP(0xc0012a6720, 0x7fe751fc9130, 0xc00000e008, 0xc00012a700)
	/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1995 +0x44
github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f00e0, 0x7fe751fc9130, 0xc00000e008, 0xc00012a700)
	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7fe751fc9130, 0xc00000e008, 0xc00012a500, 0xc0012a66e0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0005e6580, 0x7fe751fc9130, 0xc00000e008, 0xc00012a500, 0xc0012a66e0)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xf14ee0, 0xc0005e6580, 0xc0005e65e0, 0x7fe751fc9130, 0xc00000e008, 0xc00012a500)
	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
github.com/documize/community/server.(*middleware).cors(0xc000117440, 0x7fe751fc9130, 0xc00000e008, 0xc00012a500, 0xc0012a66a0)
	src/github.com/documize/community/server/middleware.go:55 +0x442
github.com/documize/community/vendor/github.
</code>

**Comment by HarveyKandola** [comment]
See if this helps:

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/customizing-documize?currentPageId=WS3-rjltKgABVdLe&source=conversion

**Comment by kt1024** [comment]
it works, thank you.
