### ISSUE TITLE
Space between blank sections is too important

### ISSUE THREAD

**Issue by Nexoz** [documize/community#253]
Hi,

When you use blank sections into a document to provide more structuration, like a blank 2., a blank 2.1 (only for titles) and then a 2.1.1 with text, there is a big waste of space between titles, reducing global readability.

For instance, there is a document we have, and it takes almost the whole page rendered on a 1080p screen :

![image](https://user-images.githubusercontent.com/16245319/56662907-484aa800-66a5-11e9-89c4-9c8a55a64ad9.png)

Thanks for your consideration

**Comment by mcmatts** [comment]
Completed for next release.
