### ISSUE TITLE
[Feature Request] Long section names get cropped in table of contents

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#254]
![long-section](https://user-images.githubusercontent.com/633268/56667185-5a175580-667b-11e9-952b-5cd601e672a5.png)

A nice to have would be for the section names to word wrap and be fully visible in the table of contents.

![long-space](https://user-images.githubusercontent.com/633268/56667483-e7f34080-667b-11e9-8c58-bddb0a1841c2.png)

Same for space names when clicking the back to space UI.

**Comment by HarveyKandola** [comment]
We're actually re-working the navigation next. Part of that work should also resolve the ToC issue.

**Comment by HarveyKandola** [comment]
Done for next release.
