### ISSUE TITLE
[Bug Report] Secure external link renders incorrectly and logs out users

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#255]
Steps to repro:
1. Log in to a Documize instance
2. Create a document
3. Share document by secure external link
4. Open document via shared secure external link

Results:
Document renders incorrectly.

<img width="661" alt="bad_page" src="https://user-images.githubusercontent.com/633268/56669954-f3e10180-667f-11e9-915d-6a010cf1dbbc.png">

Refresh the page and the Document renders correctly, but the user gets logged out.

<img width="771" alt="refreshed-bad-page" src="https://user-images.githubusercontent.com/633268/56670106-39053380-6680-11e9-9f7e-a3b10e3dc7e8.png">

**Comment by HarveyKandola** [comment]
Fixed for next release -- due by end of this week.

**Comment by HarveyKandola** [comment]
See v2.4.1+
