### ISSUE TITLE
[Feature Request] Allow login via local DB and LDAP simultaneously

### ISSUE THREAD

**Issue by avkhozov** [documize/community#256]
For now documize allow auth via built-in db or via LDAP, but not together. We want to have one local admin user and other user from LDAP. Is it possible? It can also be useful while you have problems with LDAP.

**Comment by koshia** [comment]
+1 for this.

**Comment by sauls8t** [comment]
We have a solution for this -- should make it into next release...

**Comment by HarveyKandola** [comment]
Done for next release.
