### ISSUE TITLE
Installation guide scripts are missing

### ISSUE THREAD

**Issue by CorruptComputer** [documize/community#259]
I have been attempting to get my documize instance up and running but I am struggling to get it connected to my database. The installation guide links to these scripts, however the page does not exist: https://docs.documize.com/link/document/WZrRLwxO7wAB3JOa

**Comment by HarveyKandola** [comment]
To be clear, here are the two docs:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/VzSL8cVZ4QAB2B4Y/d

Did I miss your point?

**Comment by CorruptComputer** [comment]
The link to the database scripts on that page you linked leads to a 404. The database has been giving me hell to setup, with the only error given as "connection refused" so I was hoping to reference those scripts to see what I was missing.

**Comment by HarveyKandola** [comment]
Send an email to supportATdocumizeDOTcom and we can help out.

**Comment by HarveyKandola** [comment]
The link you referenced is no longer required.

Sometimes, you have to allow connections from IP/machines, like MySQL:

![image](https://user-images.githubusercontent.com/971717/56947433-1a41e980-6b25-11e9-9277-129447a6274e.png)
