### ISSUE TITLE
Default Hypertext Links Poor Styling

### ISSUE THREAD

**Issue by immersivegamer** [documize/community#261]
I have two, three-ish, problems with the default hypertext styling:

1. Does not easily stand out from normal text, hard to tell a link is not just plain text.
1. Barely noticeable text change on mouse order, hard to tell that link is interactive even though mouse cursor changes.
1. Breaks conventions of blue colored and/or underlined text = hyperlink. (this is lower than the above two, but for example the bread crumbs on this page that I am typing this into are blue and become underlined when moused over).

This is also not great since the link styling doesn't change with the theme.

In the following images the words 'Id Consequat' is the link that is actively moused over.

Current default styling:
> Green and green. 
> ![current-default](https://user-images.githubusercontent.com/32942397/57162710-a584de80-6db4-11e9-8126-50065af2c6e0.png)

Some example ideas of type of changes to improve styling:
> Classic blue and underline
> ![normal-blue-underline](https://user-images.githubusercontent.com/32942397/57162791-eb41a700-6db4-11e9-92cd-bcbd6ea6bee7.png)

> Bi-color and underlined
> ![blue-green-underline](https://user-images.githubusercontent.com/32942397/57162809-fa285980-6db4-11e9-9d65-e1577eb5f9d2.png)

> Same green but slight bold, underline for mouse over.
> ![green-bold-underline](https://user-images.githubusercontent.com/32942397/57162846-12987400-6db5-11e9-9971-ba8ba997eed5.png)

**Comment by HarveyKandola** [comment]
Valid.

We will address for next release (probably due end of this week).
