### ISSUE TITLE
Setup fails if the database name is not `documize`

### ISSUE THREAD

**Issue by akrabat** [documize/community#264]
I'm starting Documize community on Ubuntu 18.04 using:

```
$ ./documize-community-linux-amd64 -dbtype mysql -db "19ft_eosdocs:{password}@unix(/var/run/mysqld/mysqld.sock)/19ft_eosdocs" -port 5001
```

Note that the database name is `19ft_eosdocs`.

Navigating to the http://localhost:5001/setup, I fill in the details and then it crashes when trying to run an ALTER DATABSE on the `documize` database (which obviously doesn't exist). 

```
Database: processing SQL script 15
sql statement error: ALTER DATABASE documize CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
error executing SQL script 15
Error 1044: Access denied for user '19ft_eosdocs'@'localhost' to database 'documize'
```

I've pasted the full log here: https://gist.github.com/akrabat/4a83a3463c563ad9a4509a63a0c5ce7e

I'm unclear why it is changing the character set and collation as I set them up as per the section "2 Prepare SQL Database"  in the [Installation Guide](https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide).

Database is:

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper
```

**Comment by mcmatts** [comment]
Fixed for next release

**Comment by mcmatts** [comment]
Release ETA next week

/cc @HarveyKandola

**Comment by akrabat** [comment]
Thanks. I'll watch out for it and try again then.
