### ISSUE TITLE
Unable to execute GetUserByDomain

### ISSUE THREAD

**Issue by joaodotneto** [documize/community#265]
Error when i try to login or change my password, after installation.
> Unable to execute GetUserByDomain  [USER]: mssql: 'TRIM' is not a recognized built-in function name

My MSSQL Version is 2016.

**Comment by HarveyKandola** [comment]
To be clear you are using Microsoft SQL Server and have specified as such using dbtype program switch?

**Comment by joaodotneto** [comment]
Can you release a new version please?

Thanks in advance.

**Comment by mcmatts** [comment]
Try the daily dev build as v2.5.0 drops this weekend:

https://storage.googleapis.com/documize/downloads/nightly/documize-community-darwin-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-community-linux-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-community-windows-amd64.exe

https://storage.googleapis.com/documize/downloads/nightly/documize-enterprise-darwin-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-enterprise-linux-amd64
https://storage.googleapis.com/documize/downloads/nightly/documize-enterprise-windows-amd64.exe

**Comment by joaodotneto** [comment]
Thanks my friend!

**Comment by mcmatts** [comment]
Did this release fix the issue you faced?

**Comment by joaodotneto** [comment]
> Did this release fix the issue you faced?

Yes, solved!
Working 100%
