### ISSUE TITLE
Adding releases for ARM/ARM64

### ISSUE THREAD

**Issue by Alexandero89** [documize/community#267]
Hello,
would be awesome if you could add ARM and ARM64 binaries in your releases.
Especially for your enterprise edition.

I just build documize community for my Raspberry (ARM) from sourcecode.
Had to do it manually instead of just downloading it.
And had to use community edition instead of enterprise one.

Thanks.

**Comment by HarveyKandola** [comment]
You are running Linux and currently using something like the following command to compile?

```
env GOARCH=arm64 GOOS=linux go build ....
```

Do you specify GOARM value?

https://github.com/golang/go/wiki/GoArm

**Comment by Alexandero89** [comment]
Yes, i am running on linux and compiled it on my amd64 for my raspberry arm with:
`env GOARCH=arm GOOS=linux go build .... `
Note: I used arm not arm64, but arm64 should also work.

And i didn't use any GOARM values. Worked out of the box with the build command from your build.sh

**Comment by HarveyKandola** [comment]
Thanks for confirming -- updating build scripts now and will publish new downloadable builds today!

**Comment by Alexandero89** [comment]
Wow awesome. Thank you!

**Comment by mcmatts** [comment]
I just revised the 2.5.0 release to include downloadable binaries for both ARM/ and ARM64.

@HarveyKandola push out Enterprise build onto Documize.com.

**Comment by HarveyKandola** [comment]
Enterprise downloads for ARM:

https://www.documize.com/downloads/
