### ISSUE TITLE
Complied file (AMD) does not contain the changes from dev

### ISSUE THREAD

**Issue by isgeorgiev** [documize/community#269]
Hey all, 

I am trying to integrate the knowledge base with HubSpot so people can contact me if something is not clear and so on. However, whenever I build from source the compiled file does not contain the changes. In the embed folder I see the changes in the file, however when I run the server with the compiled file from /.bin everything is default.

System specs:
- Ubuntu 18.04
- MySQL database 

I should be missing something :-) Can someone help with this?

BR,
Iliya

**Comment by HarveyKandola** [comment]
Are you building using this script?

https://github.com/documize/community/blob/master/build.sh

**Comment by isgeorgiev** [comment]
Yes, I build this script, I only excluded some of the editions since I do not need them, like Windows and the ARM 

Output of the script:
`Build process started Tue May 21 09:47:20 UTC 2019
Building Ember assets...
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Environment: production
⠸ Building[WARN] (broccoli-uglify-sourcemap) Minifying "assets/vendor.js" took: 41491ms (more than 20,000ms)
cleaning up...
Built project successfully. Stored in "/home/community/gui/dist-prod".
Copying Ember assets...
Generating in-memory static assets...
Compiling for Linux...
Finished.
`

**Comment by HarveyKandola** [comment]
There is your issue I think:

```
Building Ember assets... Could not start watchman Visit https://ember-cli.com/user-guide/#watchman for more info
```

**Comment by isgeorgiev** [comment]
I did install watchman as well but it is not recognized by Ember, not sure why yet. But isn't the watchman used only when developing to better track the files and serve them to the dev server ?

**Comment by isgeorgiev** [comment]
Hey I got the watchman to work, however, it is still not working. Any ideas? I am changing mainly the index.html in the /gui/app directory. Nothing is changing :-|

**Comment by HarveyKandola** [comment]
Which files are you changing?

**Comment by isgeorgiev** [comment]
index.html at /gui/app 
I can confirm that after running the build script the changes are as well in the dist and dist-prod, but not in the binary file

**Comment by HarveyKandola** [comment]
OK, drop an email to supportATdocumizeDOTcom and one of the team will reach out to you.

**Comment by CrashBandicoot** [comment]
@isgeorgiev good day, I faced the same issue, were you able to figure it out? If yes I think it could be useful to provide a solution here for other developers who fill face this issue in the future

**Comment by sauls8t** [comment]
Install Watchman:

https://ember-cli.com/user-guide/#watchman

And use ```ember serve``` command from the ```gui``` folder.

**Comment by CrashBandicoot** [comment]
@sauls8t thank you for your reply. I have installed watchman but the issue still persists. Also, in the dev mode (running ember serve) the application contains my updates, the issue appears when I run ./build.sh script to create a binary executable
