### ISSUE TITLE
Cloning/Moving content between spaces don't update the counters in homepage

### ISSUE THREAD

**Issue by veloso** [documize/community#274]
Initially I was using only one Space. Then I decided to subdivide my contents and created several Spaces. So I used the "Move to another space" function to move the contents to a new Space. However after moving in the new Space on the home page the "ITEMS" counter remains "0".

The same behavior occurs when creating a new Space and choosing the "Clone Space" option. Documize creates the new Space with the categories of the old Space but on the homepage the "CATEGORIES" counter remains "0".

Documize Community Edition v2.5.1 (build 190516105625).
OS: Ubuntu Server 18.04
DB: MariaDB 10.3.12

**Comment by evitalis** [comment]
I can confirm this behavior on a new community instance.

**Comment by HarveyKandola** [comment]
Yup, we have a couple of edge cases on this.

We are working on background workers that will handle:

1. Space counts calcs (this issue)
2. Periodic backup see #257 
3. Email alerts/reports subscription notifications.
