### ISSUE TITLE
Going back to spaces page

### ISSUE THREAD

**Issue by mzn88** [documize/community#275]
Congratulations on this great innovative software.

A simple request but I find essential. When you go inside a content, there's a "back" button at the top left where it takes you back to the space where the content is.

I would like to see another back button within the space that takes you to the list of spaces in which that space is labeled under (not the complete list of spaces). Currently, I would have to click the spaces symbol on the left then I have to filter by the desired label.

**Comment by HarveyKandola** [comment]
That's already done for next release.

![image](https://user-images.githubusercontent.com/971717/58327415-77307700-7e27-11e9-95eb-3780b112b795.png)
