### ISSUE TITLE
[bug] Rust code blocks missing syntax highlighting

### ISSUE THREAD

**Issue by evitalis** [documize/community#276]
I used the predefined code block then syntax highlighting is missing for Rust code. I compared to Python which does work.

In both cases the highlighting seems more correct if using the rich text editor.

**Comment by HarveyKandola** [comment]
Did you mean the Code section type is not correct for Rust?

**Comment by evitalis** [comment]
@HarveyKandola Create a new section in a document and choose <code> you will see what I mean if you pick Rust. There is no syntax highlighting at all,thus meaning it does nothing so the behavior is not correct or expected.

**Comment by mcmatts** [comment]
Fixed for next release.
