### ISSUE TITLE
[Feature Request] Spaces: Pinned Documents

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#278]
As our spaces become more and more populated, it would be nice to be able to pin a set of documents to the top of a space with some distinguishing visual features to help guide new users.

**Comment by HarveyKandola** [comment]
More than just pinning spaces, we'll have to provide ordering so as control the sequence of pinned documents.

**Comment by JRWilding** [comment]
Just to note, if your documents are ordered alphabetically, adding - will order it to be first.. might be helpful for you until this is released

**Comment by HarveyKandola** [comment]
So the ordering/pinning would default to all documents view, with no category selected. This is where we land when navigating to a space.

When selecting a category, do the pinned/ordered documents do not apply? Think not, but thoughts welcome before implementation beings...

**Comment by erhlee-bird** [comment]
Personally, it sounds good to me for the pinned documents to start for only the all documents view.

My specific desire is to help new users. If a user is knowledgeable enough to select categories, they are probably not in the group that I am trying to guide.

**Comment by erhlee-bird** [comment]
@HarveyKandola @sauls8t, just upgraded. The feature is great. Thanks so much!
