### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by johnstontrav** [documize/community#280]
Hey guys,

When I hit "Complete Setup" on the /setup page im getting this error in console:

DB: mariadb
OS: Debian 9

Database: processing SQL script 0
sql statement error: CREATE TABLE IF NOT EXISTS `user` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`refid` CHAR(16) NOT NULL COLLATE utf8_bin,
	`firstname` VARCHAR(500) NOT NULL,
	`lastname` VARCHAR(500) NOT NULL,
	`email` VARCHAR(250) NOT NULL UNIQUE,
	`initials` VARCHAR(10) NOT NULL DEFAULT "",
	`password` VARCHAR(500) NOT NULL DEFAULT "",
	`salt` VARCHAR(100) NOT NULL DEFAULT "",
	`reset` VARCHAR(100) NOT NULL DEFAULT "",
	`active` BOOL NOT NULL DEFAULT 1,
	`created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`revised` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_refid PRIMARY KEY (refid),
	UNIQUE INDEX `idx_user_id` (`id` ASC))
DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
ENGINE = InnoDB;
error executing SQL script 0
Error 1071: Specified key was too long; max key length is 767 bytes

Note:  I created the db with with command:

CREATE DATABASE documize CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

**Comment by johnstontrav** [comment]
Just to follow up.  I was able to get it running using pgres.

**Comment by HarveyKandola** [comment]
Glad you got it working with PG.

The error in question is probably due to an older version of MariaDB -- we support 10.3.0+
