### ISSUE TITLE
Subsection indents

### ISSUE THREAD

**Issue by johnstontrav** [documize/community#281]
Hey,

can you add an option indent subsections?

<img width="933" alt="Sharing_Indicator" src="https://user-images.githubusercontent.com/7200330/58609248-44d0bf00-82ea-11e9-93ae-86fa020dba2a.png">

**Comment by HarveyKandola** [comment]
We're actually already working on it.

**Comment by HarveyKandola** [comment]
Done for next release.

**Comment by johnstontrav** [comment]
thanks guys.
