### ISSUE TITLE
docs unable to be deleted

### ISSUE THREAD

**Issue by spectrumzhang** [documize/community#288]
I only able to delete it from database, I have use enterprise 10 free user version, pleae check it.

![image](https://user-images.githubusercontent.com/50335164/59945676-e509a600-949a-11e9-9380-23a8fc3bcd1f.png)

**Comment by HarveyKandola** [comment]
Did you save the free activation key ?

**Comment by spectrum-zhang** [comment]
of course i did

**Comment by HarveyKandola** [comment]
Thanks for confirming. 

Looks like you are running PostgreSQL.

So document is still in the space even after deleting. Anything in syslog/console output?

**Comment by spectrum-zhang** [comment]
I have removed it, will re-deploy it later once there is anything wrong that I will get back here, so don't close this issue please.

**Comment by spectrumzhang** [comment]
@HarveyKandola  just reinstalled it and seems not problem right now.

by the way, can i use supervisor to keep documize start automaticly after system restarted? 

also if there is update of documize, how can I keep up to update?

**Comment by HarveyKandola** [comment]
OK, let us know if the issue persists.

Yes, you can use whatever OS specific mechanism to run Documize as a background service that starts automatically after OS boot-up.

Upgrading to Documize is just a case of replacing the binary:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/W316KbJ3xwAB8UmO/self-host-upgrade-process
