### ISSUE TITLE
[Feature Request] Site Message Enhancements

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#291]
The Site Message is one of the only places I can pass immediately useful information to visitors of my Documize instance. I could possibly prevent them from aimlessly wandering, put up notices of planned system outages, describe quick procedures to get in contact with admins, etc.

It would be extremely helpful to be able to flesh the quick introduction blurb out even just a tiny bit more.

1. I would like to be able to use newlines to break up even two or three lines of content.
2. I would like to embed clickable links in the Site Message.
3. I would like to be able to bold/italicize font.

**Comment by sauls8t** [comment]
That site message entry box is being changed to Rich Text for next release.
