### ISSUE TITLE
creating new empty canvas it's should be displayed 

### ISSUE THREAD

**Issue by spectrumzhang** [documize/community#293]
Please see the video, under space, while I create a new canvas and this new canvas it's should be displayed even it's empty content as logically. if not displayed I will lost it and can't find it(not displayed) from left menu (TABLE OF CONTENTS)quickly, and only able to find it from "Reporting & Analytics" area, this is will be orphan documents and possibly delete it by mistake.

by the way, if the space able to moving down/up by hand then will be a great function.

I am using PostgreSQL database to have such issues.

please fix this issue so I can use documize asap.

**Comment by spectrumzhang** [comment]
looks unable to uploading files/photos, I have send you email to hello@documize.com with subject"issue293 video/photos"

**Comment by HarveyKandola** [comment]
Not sure I follow your issue -- send email to supportATdocumizeDOTcom

**Comment by spectrumzhang** [comment]
resent to supportATdocumizeDOTcom
