### ISSUE TITLE
is mysql5.6 able to running documize?

### ISSUE THREAD

**Issue by spectrumzhang** [documize/community#294]
also is that below syntax is correct for MySQL to deploy?
please correct and help me,thanks.

./documize-enterprise-linux-amd64  -port = 5001 -type = "mysql"  -db = "user:password@localhost:3306/db_name " salt = "tasdfddky8cdTNx3"

**Comment by HarveyKandola** [comment]
Nope. It's 5.7.10+ as per the install docs:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide

**Comment by spectrumzhang** [comment]
yes, I just asking.
