### ISSUE TITLE
unable to edit (see picture attached)

### ISSUE THREAD

**Issue by spectrumzhang** [documize/community#295]
![image](https://user-images.githubusercontent.com/50335164/60539378-26257400-9d3f-11e9-9dff-f020282dddee.png)

**Comment by sauls8t** [comment]
What are you permissions for the space?

**Comment by spectrumzhang** [comment]
I create one user/password with admin permission and send it to you: support@documize, there is a lot of problem with it.

**Comment by sauls8t** [comment]
We have not received any email -- I think you might have missed the ".com" from the email address?

We think you have not setup/installed Documize correctly as you seem to have major issues all the time.

**Comment by spectrumzhang** [comment]
of course not missing anything for the email address.

I use to download from your website, is that version is some problem? should I go to GitHub to download community version? what's the difference between community and free 10 user enterprise?


![image](https://user-images.githubusercontent.com/50335164/60553414-cf7f6080-9d65-11e9-95d7-aead6452bb8d.png)

![image](https://user-images.githubusercontent.com/50335164/60553454-ffc6ff00-9d65-11e9-8137-3e0c2bc262e8.png)

**Comment by spectrumzhang** [comment]
@sauls8t any update? do I need change to community version since this is person documents site .

**Comment by sauls8t** [comment]
No -- enterprise should be fine as long as you saved the activation key(?).

**Comment by sauls8t** [comment]
Still not received any email from you.

**Comment by spectrumzhang** [comment]
Yes, of course I saved the key for enterprise version no doubts.

here I give to you directly for testing, and there is no email bonuced, we sent it from domain: smart very dot com
wwwdotkrisdiarydotcom 
user: davis
password: DavisdocumizeABC

**Comment by sauls8t** [comment]
What is the username (email)?

**Comment by spectrumzhang** [comment]
sorry, missed it, here you are: davis@davis.com

**Comment by sauls8t** [comment]
Can you provide space manage permissions?

**Comment by spectrumzhang** [comment]
it's admin permission:

or you can use admin a/c directly: krisDOTpingAT163DOTcom
pAssw0rd: DavisdocumizeABC
![image](https://user-images.githubusercontent.com/50335164/60582853-2adc3d80-9dbc-11e9-96e1-724bb2225efd.png)

**Comment by sauls8t** [comment]
I don't think you understand.

That is global admin permissions.

There are also space level permissions that control things like editing.

I just created a new space , new document, with sections and editing works just fine.

https://www.krisdiary.com/s/bke7pa198s8tkl5efcjg/test/d/bke7pe998s8tkl5efckg/demo

Click the cog/gear icon top right corner of space page:

![image](https://user-images.githubusercontent.com/35658733/60583196-3f9bdf80-9d82-11e9-94c6-2890ae13e7ac.png)

See *space* permissions:

![image](https://user-images.githubusercontent.com/35658733/60583223-50e4ec00-9d82-11e9-96c6-204294ff1f03.png)

**Comment by sauls8t** [comment]
We are not saying space creating is the problem -- the issue is likely space level permissions. Space was created to test document editing.

We have stated a couple of times in the issue: **where is the screenshot of space permissions?**

**Comment by spectrumzhang** [comment]
I am using creator a/c to do such job, is that first a/c has permission issue?

**Comment by sauls8t** [comment]
One last time...

Can we have screenshot of space permissions, please?

**Comment by spectrumzhang** [comment]
![image](https://user-images.githubusercontent.com/50335164/60584076-d090ac00-9dbe-11e9-9c91-c68939170c2f.png)

**Comment by sauls8t** [comment]
Outcome:

* Only user Kris Lee can see and edit things in the space
* No other user can edit anything in the space

**Comment by spectrumzhang** [comment]
again!!!! I use kris lee create space and edit its documents by it.
and kris lee is first user which top admin permission.

**Comment by sauls8t** [comment]
If you want *other users* to edit any document in that space then you need to invite/add them to that space.

**Comment by spectrumzhang** [comment]
so for the first user of admin of entire website, it's no permission to editing created space/documents?

**Comment by sauls8t** [comment]
Sorry, I am really struggling with your English.

**Comment by spectrumzhang** [comment]
kris lee - the first user of documize and should be admin well.

then I use kris lee - the first user to created space but unable to edit the document of that space. 
and even the documents unable to displayed.
