### ISSUE TITLE
LDAPS support

### ISSUE THREAD

**Issue by irfanjunaid** [documize/community#296]
Hi,
I am trying to enable LDAP authentication for the documize that SSL enabled. I tried prefixing with ldaps://ldap.example.com but not change. Using the port as 636. I am seeing this error:

> Connecting to LDAP server ldap.example.com:636
> Error: unable to fetch LDAP users: unable to execute user filter: unable to read LDAP response packet: unexpected EOF
> unable to execute user filter: unable to read LDAP response packet: unexpected EOF

Could you please help me out on whats wrong? I tried checking and the IP & port are reachable from the server.

**Comment by sauls8t** [comment]
Did you try to test the same connection details using Apache Directory Studio as detailed here?

docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/bh2r67i1b54as00dsb50/authenticating-with-active-directory-ldap?currentPageId=bh2rcki1b54as00dsb80

What did you set the encryption mode to?

**Comment by irfanjunaid** [comment]
Hi, thanks for the reply! I use Apache Directory Studio to manage the LDAP... I am using SSL mode for encryption. But there is only starttls in the documize encryption options. SSL is missing in the options. I tried prefixing **ldaps://** but that gives error on additional colons being present.

**Comment by sauls8t** [comment]
That's all we have at the moment -- feel free to send a pull request for SSL!
