### ISSUE TITLE
[Feature] - Language Support: Read the same document in different languages

### ISSUE THREAD

**Issue by fromage9747** [documize/community#300]
### Summary: 
Something that I would like is the ability to have the same document in multiple languages and the ability to easily switch between them.

### Description: 
For example, I have a KB article in English, Chinese and Russian.  A Chinese user accesses my Documize instances and changes the language to Chinese.  The document is either auto-translated using Google Translate or it is flipped to the pre-defined document in Chinese that I have had pre-translated.

Kind of like how ngx-translate works in Angular.

### Workaround:
Currently, if I had to do this I would need to set up a separate landing page where the user is prompted to pick their language.

When the user selects the language that they want, it then redirects to a specific separate instance of Documize that has the documents already written in the language that the user requires them in.

**Comment by HarveyKandola** [comment]
You could try to use Versions within Documents to represent languages?

**Comment by fromage9747** [comment]
@HarveyKandola Thanks for the workaround, however, this is only available in the Enterprise edition.
