### ISSUE TITLE
GeneratePDF failed

### ISSUE THREAD

**Issue by 3mb3dw0rk5** [documize/community#301]
version: Enterprise Edition v3.1.1 (free version, activated)
db: mariadb 10.4
os: docker

Currently running an enterprise installation inside a docker container. Also created a https://hub.docker.com/r/documize/conversion alongside.

PDF generation throws the following error in logs:

> conversion_1  | time="2019-07-30T06:55:15Z" level="info" msg="DEBUG command timeout" env="Non-production" 
conversion_1  | time="2019-07-30T06:55:15Z" level="error" msg="GeneratePDF failed" stack="goroutine 17 [running]:\ngithub.com/documize/api/wordsmith/log.Error(0x863002, 0x12, 0x8ed860, 0xc00001eec0)\n\tsrc/github.com/documize/api/wordsmith/log/logger.go:52 +0xa2\ngithub.com/documize/api/export.GeneratePDF.func1(0x8f4a40, 0xc00037c000, 0xc000374000)\n\tsrc/github.com/documize/api/export/pdf.go:131 +0xab8\ngithub.com/documize/api/export.CrossOriginResourceSharing(0x8f4a40, 0xc00037c000, 0xc000374000, 0x882890)\n\tsrc/github.com/documize/api/export/pdf.go:32 +0x404\ngithub.com/documize/api/export.GeneratePDF(0x8f4a40, 0xc00037c000, 0xc000374000)\n\tsrc/github.com/documize/api/export/pdf.go:37 +0x4b\nnet/http.HandlerFunc.ServeHTTP(0x882898, 0x8f4a40, 0xc00037c000, 0xc000374000)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1995 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000103f80, 0x8f4a40, 0xc00037c000, 0xc000374000)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2375 +0x1d6\nnet/http.serverHandler.ServeHTTP(0xc0002cd6c0, 0x8f4a40, 0xc00037c000, 0xc000374000)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc0003640a0, 0x8f5640, 0xc000344140)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2884 +0x2f4\n" env="Non-production" error="conversion timelimit exceeded" 
conversion_1  | time="2019-07-30T06:55:15Z" level="error" msg="GeneratePDF failed" env="Non-production" error="conversion timelimit exceeded" stack="goroutine 17 [running]:\ngithub.com/documize/api/wordsmith/log.Error(0x863002, 0x12, 0x8ed860, 0xc0003aa090)\n\tsrc/github.com/documize/api/wordsmith/log/logger.go:52 +0xa2\ngithub.com/documize/api/export.GeneratePDF.func1(0x8f4a40, 0xc00037c000, 0xc000374000)\n\tsrc/github.com/documize/api/export/pdf.go:132 +0xaea\ngithub.com/documize/api/export.CrossOriginResourceSharing(0x8f4a40, 0xc00037c000, 0xc000374000, 0x882890)\n\tsrc/github.com/documize/api/export/pdf.go:32 +0x404\ngithub.com/documize/api/export.GeneratePDF(0x8f4a40, 0xc00037c000, 0xc000374000)\n\tsrc/github.com/documize/api/export/pdf.go:37 +0x4b\nnet/http.HandlerFunc.ServeHTTP(0x882898, 0x8f4a40, 0xc00037c000, 0xc000374000)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1995 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000103f80, 0x8f4a40, 0xc00037c000, 0xc000374000)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2375 +0x1d6\nnet/http.serverHandler.ServeHTTP(0xc0002cd6c0, 0x8f4a40, 0xc00037c000, 0xc000374000)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc0003640a0, 0x8f5640, 0xc000344140)\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/usr/local/Cellar/go/1.12.6/libexec/src/net/http/server.go:2884 +0x2f4\n" 
app_1         | PDF status code 500 Internal Server Error
app_1         | export.pdf
app_1         | <nil>
app_1         | goroutine 428 [running]:
app_1         | github.com/documize/community/edition/logging.Logger.Error(0x0, 0xc000382320, 0x1, 0xd36369, 0xa, 0x0, 0x0)
app_1         | 	src/github.com/documize/community/edition/logging/logger.go:56 +0x128
app_1         | github.com/documize/enterprise/extensions/export.(*Handler).GeneratePDF(0xc00000c140, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6c00)
app_1         | 	src/github.com/documize/enterprise/extensions/export/pdf.go:171 +0x1317
app_1         | net/http.HandlerFunc.ServeHTTP(0xc00008ff70, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6c00)
app_1         | 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44
app_1         | github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00009c700, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6c00)
app_1         | 	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f7bf08600c8, 0xc000488060, 0xc0009d6a00, 0xc0004f1520)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc00062a720, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6a00, 0xc0004f1520)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xf47900, 0xc00062a720, 0xc00062a780, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6a00)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
app_1         | github.com/documize/community/server.(*middleware).cors(0xc0003fe430, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6a00, 0xc0004f1480)
app_1         | 	src/github.com/documize/community/server/middleware.go:55 +0x442
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0003fed90, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6a00, 0xc0004f1480)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xf47900, 0xc0003fed90, 0xc00062a760, 0x7f7bf08600c8, 0xc000488060, 0xc0009d6a00)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc0001331d0, 0x7f7bf08600c8, 0xc000488050, 0xc0009d6a00)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:96 +0xec
app_1         | github.com/documize/community/vendor/github.com/gorilla/handlers.ProxyHeaders.func1(0x7f7bf08600c8, 0xc000488050, 0xc0009d6a00)
app_1         | 	src/github.com/documize/community/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x10d
app_1         | net/http.HandlerFunc.ServeHTTP(0xc0004f1460, 0x7f7bf08600c8, 0xc000488050, 0xc0009d6a00)
app_1         | 	/usr/local/Cellar/go/1.12.7/libexec/src/net/http/server.go:1995 +0x44
app_1         | github.com/documize/community/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00009c2a0, 0x7f7bf08600c8, 0xc000488050, 0xc0009d6a00)
app_1         | 	src/github.com/documize/community/vendor/github.com/gorilla/mux/mux.go:159 +0x105
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.Wrap.func1(0x7f7bf08600c8, 0xc000488050, 0xc0009d6300, 0xc0004f1440)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:46 +0x4d
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc00058c9a0, 0x7f7bf08600c8, 0xc000488050, 0xc0009d6300, 0xc0004f1440)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:29 +0x4e
app_1         | github.com/documize/community/vendor/github.com/codegangsta/negroni.middleware.ServeHTTP(0xf47900, 0xc00058c9a0, 0xc00058ca00, 0x7f7bf08600c8, 0xc000488050, 0xc0009d6300)
app_1         | 	src/github.com/documize/community/vendor/github.com/codegangsta/negroni/negroni.go:38 +0x9c
app_1         | github.com/documize/community/server.(*middleware).cors(0xc0003fe430, 0x7f7bf08600c8, 0xc000488050, 0xc0009d6300, 0xc0004f1420)
app_1         | 	src/github.com/documize/community/server/middleware.go:55 +0x442
app_1         | github.com/documize/community/vendor/github.com/codegangs

**Comment by 3mb3dw0rk5** [comment]
Here is the content of documize-pdf.log

> {"level":"info","message":"Launching Puppeteer for http://localhost:8008/s/bkvtdgmes9ueuokft360/bkvtdgmes9ueuokft360/d/bkvuijues9u7fj21u440/bkvuijues9u7fj21u440"}
{"level":"info","message":"App version 3.1.1"}
{"level":"info","message":"Await selector is .master-grid-container"}
{"level":"info","message":"Set Viewport"}
{"level":"info","message":"Going to app http://localhost:8008"}

**Comment by 3mb3dw0rk5** [comment]
Found out what the issue have been. It seems that the conversion container tries to access the documize container with the url http://localhost:8008 which is obviously not reachable as localhost is the conversion container itself.
When I access the documize container with the docker-internal-ip it all works fine

**Comment by HarveyKandola** [comment]
Also see this:

docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/customizing-documize?currentPageId=WS3-rjltKgABVdLe

Use v2.7.2 of Conversion Docker image and see DNS notes:

https://hub.docker.com/r/documize/conversion

**Comment by 3mb3dw0rk5** [comment]
The docs site is not nearly helpful enough. The main issue is that documize is not working with the localhost domain when used in a docker-compose environment with separate network

**Comment by HarveyKandola** [comment]
Got it.

Can you share your docker compose file here?

If not, email support supportATdocumizeDOTcom
