### ISSUE TITLE
Missing `embed/bindata` build in version 3.1.2

### ISSUE THREAD

**Issue by Ma27** [documize/community#304]
In #302 I filed a simple patch which properly renders HTML from Markdown sections when previewing the content (as it happens when requesting the current document) which is part of the latest release [`v3.1.2`](https://github.com/documize/community/releases/tag/v3.1.2).

In my PR I mentioned that I didn't commit the changes in `embed/bindata.go` that were generated by `go-bindata` while running `./build.sh` locally. However when taking a look at the `embed/` directory, it seems as nothing happened between 3.1.1 and 3.1.2: https://github.com/documize/community/compare/v3.1.1...v3.1.2

This also explains why my patch doesn't work when deploying documize-community 3.1.2 in contrast to my local development setup. Please correct me if I'm totally missing something, but to me it seems as the easiest fix would be to release a `3.1.3` with an updated `embed/bindata.go`.

**Comment by HarveyKandola** [comment]
I just asked @sauls8t to commit the bindata assets as per the 3.1.2 build -- please can you check your side?

**Comment by Ma27** [comment]
@HarveyKandola Just deployed a documize-community 3.1.2 with 02d478c6ddf308e2e9e44230243b4b194899bf59 on top and it works fine, thanks!

Is it possible to tag a new release with this patch? :)

**Comment by HarveyKandola** [comment]
3.1.3 is just around the corner!

**Comment by Ma27** [comment]
@HarveyKandola  Sorry to bother you again, but may I ask if there's anything that keeps you from publishing 3.1.3? :)

**Comment by HarveyKandola** [comment]
> @HarveyKandola Sorry to bother you again, but may I ask if there's anything that keeps you from publishing 3.1.3? :)

Enterprise edition would also get bumped and causes our paying customers to upgrade their installations, but no new fixes/features.

Hence, once ready, v3.1.3 will contain fixes and updates that customers can see a reason to upgrade.

Hope that clears it up!
