### ISSUE TITLE
Document permissions - I can read document without read permissions

### ISSUE THREAD

**Issue by ojanovsky** [documize/community#310]
I have two categories in space. "Internal" and "public". Customer has permissions for public category only.
Now I create document and assign "internal" category as administrator. 
When I loggin as customer, I open space and I can't see document, it is ok. 
But, when I know whole url, I can see document as customer without permissions.

**Comment by HarveyKandola** [comment]
Did you enable Anonymous Access under Settings -> General ?

**Comment by ojanovsky** [comment]
In general settings: "Public Spaces Viewable By Anonymous Users" is OFF

**Comment by HarveyKandola** [comment]
Thanks for the information -- we will look into this ASAP.

**Comment by HarveyKandola** [comment]
Due in 3.2.0 release, later this week.
