### ISSUE TITLE
Firefox logoff

### ISSUE THREAD

**Issue by dvoijen** [documize/community#314]
It's the same as #246 however there is no proxy in front.
Firefox users keep getting logged off if opening a document in a seperate tab.
Even when they get a email with alink, when clicking on it it loggs off everything of documize.
This is a hassle when trying to use the approve feature...

**Comment by HarveyKandola** [comment]
Cannot seem to reproduce -- will really some additional information.

Which version of Firefox? 
Using Firefox containers by any chance?

**Comment by dvoijen** [comment]
@HarveyKandola Latest update solved the issue...
Sorry, forgot to mention....
