### ISSUE TITLE
Documentation on Analytics

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [documize/community#316]
I can see that Analytics and Reporting was added on  v1.61.0 on Enterprise but I don't see where I am able to insert a tracker or see any built in analytics.

**Comment by Th3Whit3Wolf** [comment]
I have made my user able to access analytics as well.

I was originally running the team version and upgraded to enterprise(Documize is  awesome!), after upgrading I had to manually upgrade my admin(and only) user to have analytics privileges, not  sure if this is intended behavior.

**Comment by HarveyKandola** [comment]
Yup, intended behaviour to set permissions manually.
