### ISSUE TITLE
Approval not working

### ISSUE THREAD

**Issue by dvoijen** [documize/community#321]
When i edit a document that is in the state changes require approval before publication, the approver gets a email.
![image](https://user-images.githubusercontent.com/28559228/64593916-46148c00-d3af-11e9-9d0c-dddccc637d66.png)

If he than goes to the document en try to approve, nothing happens.

**Comment by HarveyKandola** [comment]
You running enterprise edition?

**Comment by dvoijen** [comment]
Yes i am.

**Comment by HarveyKandola** [comment]
Does the person see the Review changes option and then clicks Approve?

**Comment by dvoijen** [comment]
Yes he does, but clicking on accept nor reject does nothing

**Comment by HarveyKandola** [comment]
Can you send any further information (screenshots, video) to supportATdocumizeDOTcom ?
