### ISSUE TITLE
"Public Spaces Viewable By Anonymous Users" - Not Working

### ISSUE THREAD

**Issue by drewrockshard** [documize/community#323]
## Issue
"Public Spaces Viewable By Anonymous Users" is not working.  Doesn't show any spaces at all (see screenshots below)

## Software
Documize Version: v3.3.0
Platform: Docker 18.09.6 / Rancher 2.2

### Public Spaces - Enabled
![image](https://user-images.githubusercontent.com/37336/65015340-e2c2b680-d8e6-11e9-87b2-8a07f75445c8.png)

### API Meta Space - Public Access
![image](https://user-images.githubusercontent.com/37336/65015379-fff78500-d8e6-11e9-8254-a7eafd53b373.png)

### Public Access (non authenticated login), not showing any spaces
![image](https://user-images.githubusercontent.com/37336/65015411-1d2c5380-d8e7-11e9-935b-175ab0c1ead4.png)

**Comment by drewrockshard** [comment]
Update:

Interesting enough, it looks like when I create a space myself (not using the pre-existing spaces during installation), setting it to Public, it works:

#### Adding a new "Test" space, setting it to Public:
![image](https://user-images.githubusercontent.com/37336/65016233-5b2a7700-d8e9-11e9-8c32-460bab5bb503.png)

Futhermore, even more interesting, if I take the pre-existing API (or any other pre-existing spaces), set them to anything else that isn't public, save, and then set it to public, it then shows up:

#### Public (non-authenticated view) after changing API from Public, to Private, back to Public:
![image](https://user-images.githubusercontent.com/37336/65016350-a5135d00-d8e9-11e9-8d9f-8394e016efa3.png)

Would this be considered a bug or expected behavior?

**Comment by mcmatts** [comment]
Just check space has given "Everyone" view permissions?
