### ISSUE TITLE
unable to fetch request meta for / new install

### ISSUE THREAD

**Issue by Ivan-droid** [documize/community#324]
Hi, i try the Documize in my self-hosted solution, but in demilitarized zone on all version (community, enterprise) i see error "unable to fetch request meta for" . On another server, who can go to Internet, all ok. Can the Documize work without connect of internet? I tried start Documize with and without config file. Thanks

./documize-community-linux-amd64 -port=5001 -db='documize:password@tcp(localhost:3306)/documize' -dbtype=mariadb -salt=tsu3Acndky8cdTNx3  -offline 0 -logtostderr -v 3 -alsologtostderr
Configuration source: flags/environment
Database: checking state
Database: provider name MySQL
Database: provider version 10.4.8-MariaDB
Database: current version number is 31
Database: loaded 32 SQL scripts for provider MySQL
Database: 0 scripts to process
Extensions: registered 13 section types
Product: Community Edition version 3.3.0 (build 190916092538)
Web Server: starting up
Web Server: binding non-SSL server on 5001
[negroni] listening on :5001
unable to fetch request meta for www

Red Hat Enterprise Linux Server release 7.6 (Maipo)
 4.1.12-124.26.10.el7uek.x86_64

**Comment by mcmatts** [comment]
Go to Settings -> General.

Look at the Site URL Subdomain value. Maybe set it to www?

**Comment by Ivan-droid** [comment]
I can see page only on offline mode. In online mode i see blank white page after fresh installation and can't go to any configuration menu. This is http-trace http://paste.susenin.ru/41/4f910e2f82abe4da935105adbebee57a5896d9.png

**Comment by mcmatts** [comment]
What is your URL? Image is not clear.....

**Comment by Ivan-droid** [comment]
www (it's hostname), who correct resolved to inside IP-address. Tried short and FQDN, direct IP-address

**Comment by Ivan-droid** [comment]
hi, any ideas

**Comment by sauls8t** [comment]
Try http://localhost ?

**Comment by Ivan-droid** [comment]
Yes, I tried localhost, but still see the error
```
Request URL:http://localhost:5001/api/public/meta
Request method:GET
Remote address:[::1]:5001
Status code:
404
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade
```

**Comment by sauls8t** [comment]
Thanks.

404 not found error would suggest browser is unable to connect to server?
Can you ping the server?

**Comment by Ivan-droid** [comment]
> I can see page only on offline mode. In online mode i see blank white page after fresh installation and can't go to any configuration menu. This is http-trace http://paste.susenin.ru/41/4f910e2f82abe4da935105adbebee57a5896d9.png

404 is, that resource not found in server
In a link above and this, we can see, that some resources retrieved ok, but one of them no (404 error)
In the console out errors are the same

```
[***@www documize]# ./documize-community-linux-amd64 config-mysql.xml
Configuration source: config-mysql.xml
Database: checking state
Database: provider name MySQL
Database: provider version 10.4.8-MariaDB
Database: current version number is 31
Database: loaded 32 SQL scripts for provider MySQL
Database: 0 scripts to process
Extensions: registered 13 section types
Product: Community Edition version 3.3.2 (build 191014171946)
Web Server: starting up
Web Server: binding non-SSL server on 5001
[negroni] listening on :5001
unable to fetch request meta for
unable to fetch request meta for
unable to fetch request meta for
unable to fetch request meta for
unable to fetch request meta for
```


![documize](https://user-images.githubusercontent.com/55462360/67201323-b2eb5f00-f40e-11e9-81b6-e042c7b686b2.PNG)

**Comment by HarveyKandola** [comment]
Can you share you config file?

What is the value in SQL for ```dmz_org.c_domain```?

**Comment by Ivan-droid** [comment]
```
***@www documize]# cat config-mysql.xml
[http]
port = 5001
#forcesslport = 5002
#cert = "selfcert/cert.pem"
#key = "selfcert/key.pem"

[database]
type = "mariadb"
connection = "documize:password@tcp(localhost:3306)/documize"
salt = "tsu3Acndky8cdTNx3"

[install]
location = "selfhost"
```


> What is the value in SQL for `dmz_org.c_domain`?

MariaDB [documize]> select * from dmz_org;
Empty set (0.002 sec)

**Comment by HarveyKandola** [comment]
If you have no rows in ```dmz_org``` then setup process failed. This is why nothing works for you.

Did you go to http://localhost/setup and complete the process?

**Comment by Ivan-droid** [comment]
> 
> 
> If you have no rows in `dmz_org` then setup process failed. This is why nothing works for you.
> 
> Did you go to http://localhost/setup and complete the process?

Yes, i know.  Fresh installation was incomplete with this error and there are no way to complete setup at this time - only via drop/create database (and setup will be stopped with this error)

**Comment by sauls8t** [comment]
Couple of points:

1. Don't use -offline switch.
2. Please do another clean install and send us the output.

**Comment by Ivan-droid** [comment]
Create database

```
MariaDB [(none)]> CREATE DATABASE documize CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
Query OK, 1 row affected (0.001 sec)
```
Start script and go to setup

![documize-setup-1](https://user-images.githubusercontent.com/55462360/67219669-17b7b100-f431-11e9-8160-ecec83718369.PNG)
After press button to complete setup we can see blank screen

![documize-setup-2](https://user-images.githubusercontent.com/55462360/67219741-328a2580-f431-11e9-9a76-4b3989d6955d.PNG)

Console output of documize
```
[***@www documize]# ./documize-community-linux-amd64 config-mysql.xml
Configuration source: config-mysql.xml
Database: checking state
Database: provider name MySQL
Database: provider version 10.4.8-MariaDB
Database: starting setup mode for empty database
Extensions: registered 13 section types
Product: Community Edition version 3.3.2 (build 191014171946)
Serving SETUP web server
Web Server: binding non-SSL server on 5001
***
*** Go to http://localhost:5001/setup in your web browser and complete setup wizard ***
***
[negroni] listening on :5001
Database: loaded 32 SQL scripts for provider MySQL
Database: 32 scripts to process
Database: processing SQL script 0
Database: attempting legacy fallback for SQL script 0
Database: processing SQL script 1
Database: attempting legacy fallback for SQL script 1
Database: processing SQL script 2
Database: attempting legacy fallback for SQL script 2
Database: processing SQL script 3
Database: attempting legacy fallback for SQL script 3
Database: processing SQL script 4
Database: attempting legacy fallback for SQL script 4
Database: processing SQL script 5
Database: attempting legacy fallback for SQL script 5
Database: processing SQL script 6
Database: attempting legacy fallback for SQL script 6
Database: processing SQL script 7
Database: attempting legacy fallback for SQL script 7
Database: processing SQL script 8
Database: attempting legacy fallback for SQL script 8
Database: processing SQL script 9
Database: attempting legacy fallback for SQL script 9
Database: processing SQL script 10
Database: attempting legacy fallback for SQL script 10
Database: processing SQL script 11
Database: attempting legacy fallback for SQL script 11
Database: processing SQL script 12
Database: attempting legacy fallback for SQL script 12
Database: processing SQL script 13
Database: attempting legacy fallback for SQL script 13
Database: processing SQL script 14
Database: attempting legacy fallback for SQL script 14
Database: processing SQL script 15
Database: attempting legacy fallback for SQL script 15
Database: processing SQL script 16
Database: attempting legacy fallback for SQL script 16
Database: processing SQL script 17
Database: attempting legacy fallback for SQL script 17
Database: processing SQL script 18
Database: attempting legacy fallback for SQL script 18
Database: processing SQL script 19
Database: attempting legacy fallback for SQL script 19
Database: processing SQL script 20
Database: attempting legacy fallback for SQL script 20
Database: processing SQL script 21
Database: attempting legacy fallback for SQL script 21
Database: processing SQL script 22
Database: attempting legacy fallback for SQL script 22
Database: processing SQL script 23
Database: attempting legacy fallback for SQL script 23
Database: processing SQL script 24
Database: attempting legacy fallback for SQL script 24
Database: processing SQL script 25
Database: processing SQL script 26
Database: processing SQL script 27
Database: processing SQL script 28
Database: processing SQL script 29
Database: processing SQL script 30
Database: processing SQL script 31
unable to fetch request meta for
```

**Comment by sauls8t** [comment]
What data do you have in table ```dmz_org```?

**Comment by susenin** [comment]
```
MariaDB [(none)]> use documize;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [documize]> show tables;
+----------------------+
| Tables_in_documize   |
+----------------------+
| dmz_action           |
| dmz_audit_log        |
| dmz_category         |
| dmz_category_member  |
| dmz_config           |
| dmz_doc              |
| dmz_doc_attachment   |
| dmz_doc_comment      |
| dmz_doc_link         |
| dmz_doc_share        |
| dmz_doc_vote         |
| dmz_group            |
| dmz_group_member     |
| dmz_org              |
| dmz_permission       |
| dmz_pin              |
| dmz_search           |
| dmz_section          |
| dmz_section_meta     |
| dmz_section_revision |
| dmz_section_template |
| dmz_space            |
| dmz_space_label      |
| dmz_user             |
| dmz_user_account     |
| dmz_user_activity    |
| dmz_user_config      |
+----------------------+
27 rows in set (0.001 sec)

MariaDB [documize]> select * from dmz_org;
Empty set (0.002 sec)

```

**Comment by sauls8t** [comment]
Do you have any data in ```dmz_docs```?

**Comment by Ivan-droid** [comment]
MariaDB [documize]>  select * from dmz_doc;
Empty set (0.001 sec)

MariaDB [documize]> select * from dmz_section;
Empty set (0.001 sec)

MariaDB [documize]> select * from dmz_user;
Empty set (0.002 sec)

**Comment by HarveyKandola** [comment]
@Ivan-droid  @susenin 

So tables are create but no data.

Unable to reproduce on either MariaDB 10.3 or 10..4!

Try setting as follows:

```
ALTER database documize CHARACTER SET utf8 COLLATE utf8_general_ci; 
```

**Comment by mcmatts** [comment]
@Ivan-droid @susenin

Can you try another database provider? MySQL or PostgreSQL?
