### ISSUE TITLE
Permissions gone after upgrade to 3.1.1

### ISSUE THREAD

**Issue by enoch85** [documize/community#329]
## Steps to reproduce
1. Upgrade from 3.0.0 to 3.1.1 (build 190925093840)  by replacing the package as usual.

## Expected behavior
Permissions should be the same as before and set permissions should work

## Actual behavior
- When logging in as a regular user who has admin permissions to a certain space (Bredablick in this case) nothing is shown (not visible)
- Checking the permissions I can see that they are set, but it doesn't apply, no spaces are visible.

## What I've tried
- Sync LDAP manually
- Resync index (desperate)
- Re-save the permissions for the Bredablick space
- Rebooted the server

## What might be the cause
We recently changed domain from XXX.se to YYY.se for all users in AD. But, all other systems with LDAP connected works as usual so I would be surprised if this was the cause.

**Comment by enoch85** [comment]
Issue solved. It turned out to be the domain change that was the cause.

Adding the same user again and set the permissions on that new user worked, resulting in 2 users though.

Maybe improve LDAP a bit to avoid these kinds of issues?

**Comment by enoch85** [comment]
This issue is not solved. 

Now I noticed that I'm not admin anymore and I can only see my own space. Need to revert from backup.

Maybe for a separate issue, but it would be nice to be able to see which email address that are connected to the user in LDAP when adding new users to Spaces by searching LDAP.

**Comment by HarveyKandola** [comment]
Not 100% sure on what you are saying.

We compare/match users using email address:

https://github.com/documize/community/blob/2477c36f11ffe7f871f3eb3d85e8287160d8220a/domain/auth/ldap/endpoint.go#L204

**Comment by enoch85** [comment]
Sorry, turns out another admin remove my permissions.

> We compare/match users using email address:

Yes, but if a user changes email, in Documize that also means that you loose the permissions. 

Another thing is that when LDAP syncs again, the "new" user (same user different email) shows up two times. It would be much better if when syncing, only using the current values from LDAP, IMHO.
