### ISSUE TITLE
Github Section: repo drop-down doesn't contain all the repos it should

### ISSUE THREAD

**Issue by Lanzafame** [documize/community#33]
Attempting to add a Github Section for an organization repo and the drop-down list only contains a select few repos. This is also the case for my personal Github account as well. This is currently on the hosted version of Documize.

**Comment by HarveyKandola** [comment]
@Lanzafame 

When you first authorize Documize to access your GitHub account, it lists all the repos. Against each repo, there should be a button to grant/request access to the repo.

Try it and let us know.

v0.17 drops later today with a re-vamped GitHub section!
