### ISSUE TITLE
Section edits possible while documents 'locked'

### ISSUE THREAD

**Issue by danatkdan** [documize/community#330]
Our users have pointed out that when a document is 'locked' in Change Control setings, they can still make edits in sections, and save these. The edits are then lost if the page is refreshed.

This is confusing for the users, and problematic if someone doesn't notice a document is locked and makes a lot of edits which don't get saved anywhere.

Surely if the document is 'locked' for changes, then sections should not be editable?

**Comment by mcmatts** [comment]
Can you confirm version and edition?

**Comment by danatkdan** [comment]
self-host enterprise, v3.3

**Comment by HarveyKandola** [comment]
Thanks for the report -- fixed for next release due today.
