### ISSUE TITLE
Bug with TABLE OF CONTENTS

### ISSUE THREAD

**Issue by FuriousWarrior** [documize/community#332]
There is a bug with a sidebar. An error results in a non-working page.

![bug](https://user-images.githubusercontent.com/29947028/66916091-34b04680-f023-11e9-80fa-bb0fe9a78f96.gif)

**Comment by HarveyKandola** [comment]
Thanks for the report.

Which browser(s)?

**Comment by FuriousWarrior** [comment]
google chrome

**Comment by sauls8t** [comment]
Thanks -- cannot seem to reproduce as yet, but will check again.

**Comment by kuttnerd** [comment]
We also have an issue with the table of content, when we use the "sharing via secure link" (firefox and chrome, current versions) > the anchor-Links are not working.
![AwesomeScreenshot-2019-11-7-1573131852223](https://user-images.githubusercontent.com/8133239/68391337-b2212f80-0167-11ea-9612-c1d897abd7a2.gif)

and there seems to be an issue with ember
![image](https://user-images.githubusercontent.com/8133239/68391195-4fc82f00-0167-11ea-804e-95d3d9ddbf07.png)

**Comment by mcmatts** [comment]
@kuttnerd 

You facing two different issues? 

1. Links in table of content not working?
2. Sharing view secure link?

Screenshot is for #1 ?

**Comment by kuttnerd** [comment]
@mcmatts yep, two different issues with the "secure link" site.

1. the Gif is showing the not working links
2. the Screenshot shows the broken ember file

Currently running Documize Enterprise Edition v3.3.1 (build 190925093840)

**Comment by mcmatts** [comment]
Fixed for next release.
