### ISSUE TITLE
Show anonymous views in activity tab

### ISSUE THREAD

**Issue by taalas** [documize/community#333]
Hi!

Would it be possible to show anonymous views in the **Activity** tab?

Currently it only shows views/edits/etc by registered users. Is there another way to check, how often a document was read (possibly in a given time frame)?

**Comment by sauls8t** [comment]
Activity tab is not shown because it can contain information that should not be seen by "external" users.

**Comment by taalas** [comment]
I think you misunderstood my request.

I was not suggesting to show the Activity tab to anonymous user but to show views **by** anonymous users to registered users. Sometimes it can be benificial to not only know which registered users have viewed the content but also how many anonymous views a document got.

**Comment by HarveyKandola** [comment]
That makes sense!

Maybe the analytics dashboard can help you to see what people are viewing/searching for?
