### ISSUE TITLE
Bug with Markdown-Lists

### ISSUE THREAD

**Issue by der-mac** [documize/community#335]
Hi,

there is a bug, when one try to write lists with more than two sub-levels in a markdown-section.

You can reproduce this with the following markdown-code:

```
- foo-level 1
  - foo-level 2
    - foo-level 3
      - foo-level 4
        - foo-level 5
```

The preview is correctly rendered.
But when you save the section, the sub-level 3 is the same as sub-level 2 and sub-level-5 is the same as sub-level 4.

regards

### Environment:
Documize version: v3.4
Firefox version: 69.0.3
Chrome version: 78.0.3904.70.

### Steps:

**Code:**
![2019-10-27 10-04-20](https://user-images.githubusercontent.com/28485107/67632279-c892d580-f8a1-11e9-8a42-de639df62b2a.png)

**Preview:**
![2019-10-27 10-04-30](https://user-images.githubusercontent.com/28485107/67632281-ca5c9900-f8a1-11e9-982d-06a4045df602.png)

**Result:**
![2019-10-27 10-04-42](https://user-images.githubusercontent.com/28485107/67632284-cc265c80-f8a1-11e9-8b96-72e42cf0818d.png)

**Comment by HarveyKandola** [comment]
To be clear, the indent should be 4 spaces?

**Comment by der-mac** [comment]
The amount of indents is not the point. The Point is, that level 3 and level 5 are not indented at all.

**Comment by HarveyKandola** [comment]
@der-mac thanks.

Yes, we know that levels 3 and 5 should indent as expected. No question.

We cannot seem to reproduce and hence just asking to see how you indented.

**Comment by der-mac** [comment]
Oh ... now I can see the problem. Markdown needs 4 spaces for one indent.
I have used only 2 space.

Thank you, for your hint.
