### ISSUE TITLE
Add toast error message

### ISSUE THREAD

**Issue by ShellyXueHan** [documize/community#337]
Background:
There are some actions that non-admin do get access to but not have the privilege to conduct.

Issue:
For example, in a space, a user with `manage` and `owner` role can see and edit the `Space Meta` settings page, but no action happens after clicking on SAVE button. Found error message in console logs `Uncaught Error: Request was rejected because user is not permitted to perform this operation.`

Suggestions:
For UI improvement:
- Implement toast message for error message. 
- Or hide the options from users without correct privilege.

**Comment by mcmatts** [comment]
Can you send a screenshot?

A space owner should be able to perform all actions.

**Comment by ShellyXueHan** [comment]
We are running: Documize Community Edition v3.3.1 (build 190925093840)
User has been granted access to be the space owner+manage role:
<img width="1161" alt="user-access-on-space" src="https://user-images.githubusercontent.com/36056216/68496977-5a86d080-0208-11ea-8967-e1827be1f29d.png">

Log in as the user and edit the space metadata, clicking on save button gives the error message in browser console. But nothing show up on the page.
<img width="1668" alt="when-changing-space-data" src="https://user-images.githubusercontent.com/36056216/68496978-5a86d080-0208-11ea-9c31-fef22ed4f7df.png">

**Comment by mcmatts** [comment]
Can you upgrade to 3.4.1 release and report back.

We cannot reproduce the issue.

**Comment by ShellyXueHan** [comment]
Hey there, I've upgraded 3.4.1 but still having the same issue.
![Screen Shot 2019-11-12 at 2 49 34 PM](https://user-images.githubusercontent.com/36056216/68717605-1410d900-055c-11ea-837c-b60a15607e9d.png)

And the new finding is that the space owner has to have the `Spaces` permission in the Admin's user setting page, then they could edit the space metadata. But the description of the permission only mention about space creation, so I guess it shouldn't affect the space management? Is this expected?

For our use case, we want to create a space for a team and assign a person to be the space owner so that the team could manage it themselves. But we do not want that space owner to create other spaces. Could this be considered into the scope?

Thanks!

Shelly

**Comment by HarveyKandola** [comment]
For next release -- space admins can manage space, *without* being able to create spaces.
