### ISSUE TITLE
[Feature Request] Specify Default Categories for a Space

### ISSUE THREAD

**Issue by erhlee-bird** [documize/community#339]
We are using an organizational pattern of

```
Space

Categories
- internal (Team-only)
- public (Everyone)
```

But documents, by default, are naturally visible to anyone who has been given view permissions of a space. It would be nice to be able to set the space such that all new documents are initially set to have the "internal" (space-specific) category.

**Comment by HarveyKandola** [comment]
What happens if you assign every document a category and then select *who* can view each category?

This should hide internal docs?

**Comment by danatkdan** [comment]
Yes we have noticed this - documents with no categories set are visible to users with 'view' permissions on the space (which are necessary to be able to view docs with category-based permissions).

We would also really like default categories for a space, so that users do not inadvertently share content with other teams when creating new docs.

**Comment by sauls8t** [comment]
@erhlee-bird 

Did the suggestion of categories resolve some of the problem?

@danatkdan 

That could be useful. Couple of ways round that today:

1. Use template docs that already have categories set.
2. Set all new docs to DRAFT and require explicit publication from those that can review and publish.

**Comment by erhlee-bird** [comment]
That's how we have the workflow set up now, but the root concern is the one that @danatkdan brought up. We've had instances where users inadvertently forgot to set the category.

Configurable default categories would be a naturally enforcement of the desired policy whereas setting the category manually is reactive and allows for human error.

**Comment by sauls8t** [comment]
That's what we thought -- thanks for confirming.

Preferred route would be to apply "default" categories upon document creation (template, blank, or imported).

@erhlee-bird  @danatkdan 

Agreed?

**Comment by erhlee-bird** [comment]
Agreed

**Comment by sauls8t** [comment]
Working on this now -- due next week.

When a new document is auto-assigned categories, there is a chance the creator might not be able to see the doc after creation, because of category view permissions.

**Comment by HarveyKandola** [comment]
This has been completed for v3.5.0 release due shortly.

Note:

Categories applied to template take precedence over space level default categories.
