### ISSUE TITLE
uncontrolled page scrolling

### ISSUE THREAD

**Issue by protheusfr** [documize/community#344]
Hello,

On the last version of both Documize Community and Enterprise versions I get uncontrolled page scrolling.
For exemple, I'm on the top of the page and without any action from me, documize scroll to the bottom of the document.
Same behaviour when I clic to the menu of a bloc in the top (or middle) of the page, Documize scroll to the bottom of them and I can't access to the menu.

Same comportment with Chrome 78 and Firefox 71...

Bug or config issue ?

**Comment by mcmatts** [comment]
Any chance of a screenshot?

**Comment by protheusfr** [comment]
Will try to do one without confidential data

**Comment by protheusfr** [comment]
Please find attached an exemple with a small document (mix of rich text and markdown).
It's even more disabling on large documents.

![Enregistrementdelecran2019-12-04](https://user-images.githubusercontent.com/1698825/70149782-1cff5100-16a9-11ea-9a66-7593fb36963b.gif)

**Comment by protheusfr** [comment]
Hello @mcmatts, any idea considering the screenshot ?

**Comment by HarveyKandola** [comment]
Should be fixed very shortly. Expect new version soon...

**Comment by protheusfr** [comment]
👍
