### ISSUE TITLE
[Feature Request] PlantUML Links in diagram via SVG output

### ISSUE THREAD

**Issue by JRWilding** [documize/community#350]
This might be a significant change.
Currently links defined in PlantUMLs are rendered correctly, but since the output format is png they aren't clickable. Would be nice if they worked. I believe that if their were correctly embedded svgs it could work.

As a reference:
https://github.com/asciidoctor/asciidoctor-diagram/issues/166 https://github.com/asciidoctor/asciidoctor-diagram/issues/64

**Comment by sauls8t** [comment]
Changed rendering to SVG.

Lands in next release.
