### ISSUE TITLE
[Feature Request] More Detail on Trello Cards

### ISSUE THREAD

**Issue by JRWilding** [documize/community#351]
This might be controlled by Trello rather than yourselves.
Currently cards displayed in a Trello section only have the card title.
It would be nice to have more detail displayed per card, like labels, due dates, checklist etc.
Perhaps this would be too much effort to keep synced, but if it could be kept up to date and look more like the cards displayed in Trello itself, that'd be grand.
![image](https://user-images.githubusercontent.com/11031099/70375211-0815fe00-18f3-11ea-97f2-c076cff3cd3c.png)

**Comment by sauls8t** [comment]
We are in control of the rendering:

See the render template at the top and the card definition further down:

https://github.com/documize/community/blob/master/domain/section/trello/model.go

Closing as not a priority at the moment. PR welcome!
