### ISSUE TITLE
[Feature Request] iframe section

### ISSUE THREAD

**Issue by JRWilding** [documize/community#352]
As the AirTable section plugin uses iframes, how about a generic iframe section. Could be then used to embed other documize documents. Currently using the AirTable section I could do
![image](https://user-images.githubusercontent.com/11031099/70430385-9bc20880-1a72-11ea-92ba-7c7dd9921458.png)
I can tweak the dimensions of the frame, but if there was a url that included the content of the document rather than the whole ui that'd be nice.

**Comment by sauls8t** [comment]
Just implemented a generic IFrame section type.
