### ISSUE TITLE
PlantUML Diagram stoped working

### ISSUE THREAD

**Issue by togsen** [documize/community#354]
I can't get PlantUML to work correct after i by mistake loaded an earlier Documize version during an update. i loaded the 3.6 version back. But now PlantUML display a "broken" icon on a sample preview. When i edit an existing post the image disappears :(

how do i debug the issue?

**Comment by HarveyKandola** [comment]
Are you self-hosting Documize? If so, did you also update your Conversion service Docker container?

**Comment by togsen** [comment]
Self-hosting. Yes i did update Conversion service Docker container.

**Comment by togsen** [comment]
do i need the 3.0 or the 3.1 for documize 3.6?

**Comment by HarveyKandola** [comment]
_Self-hosting. Yes i did update Conversion service Docker container._

What version did you update to?

**Comment by togsen** [comment]
Documize Enterprise Edition v3.6.0 (build 191209123639)

**Comment by HarveyKandola** [comment]
_Self-hosting. Yes i did update **Conversion service Docker container.**_

What version of the **Conversion Service Docker container** did you update to?

**Comment by togsen** [comment]
3.1 :)

**Comment by HarveyKandola** [comment]
_3.1 :)_

Then all should OK.

Can you send screenshot to supportATdocumizeDOTcom?

**Comment by togsen** [comment]
will do.
