### ISSUE TITLE
How to remove template label from document

### ISSUE THREAD

**Issue by shardick** [documize/community#355]
Hi,
we have uploaded wrongly a document as a template but now we want to remove that attribute from the document without cancelling it.
We have just tried to copy the document but it copied also the template attribute.

Thanks in advance

**Comment by sauls8t** [comment]
Are you self-hosted or using Documize cloud?

**Comment by shardick** [comment]
Selfhosted

**Comment by sauls8t** [comment]
Quick-method:

In the SQL database please set ```dmz_doc.c_templates = 0```

**Comment by shardick** [comment]
Why are you closing it? :D
It's a missing features. Should be always possible to remove a document from templates list but from interface.

Btw, thanks.
