### ISSUE TITLE
Keycloak configuration not saved

### ISSUE THREAD

**Issue by luketainton** [documize/community#358]
Whenever I try to save my Keycloak configuration, I get the notification to say it's been saved, but the changes are reverted after one Keycloak login.

**Comment by HarveyKandola** [comment]
Which version you running and what is your DB provider?

**Comment by luketainton** [comment]
Hi @HarveyKandola!

I'm using Documize version 3.6.0 with a PostgreSQL backend.

**Comment by HarveyKandola** [comment]
Thanks.

> changes reverted after one login

We will need some additional info from you hence email supportATdocumizeDOTcom (privacy required!).
