### ISSUE TITLE
Debian systemd documizer.service

### ISSUE THREAD

**Issue by asterlab** [documize/community#359]
tried to make my own systemd .service for documize but it seems it is not working/cannot read the config/cannot fork to background. can you please help me so I can make it start at boot ?

[documizer.service.txt](https://github.com/documize/community/files/4116215/documizer.service.txt)

**Comment by apetrone** [comment]
Hi @asterlab,

It might be the Type=notify that is causing you trouble. It requires the executable to report in with systemd via sd_notify.

As Documize is just a single executable, I am using Type=simple. I had success with the systemd service below.

```
[Unit]
Description=documize
After=network.target

[Service]
Type=simple
User=documize
ExecStart="/path/to/documize-linux-amd64" "/path/to/documize.conf"

[Install]
WantedBy=multi-user.target
```

**Comment by asterlab** [comment]
Thanks I will try that

> [Unit]
> Description=documize
> After=network.target
> 
> [Service]
> Type=simple
> User=documize
> ExecStart="/path/to/documize-linux-amd64" "/path/to/documize.conf"
> 
> [Install]
> WantedBy=multi-user.target

**Comment by asterlab** [comment]
problem solved thanks
