### ISSUE TITLE
Export all Content - No documents found

### ISSUE THREAD

**Issue by Verbat** [documize/community#360]
Hello,

I'm trying to export all content via Settings - Spaces - EXPORT ALL CONTENT.
By using the Button in the Backend it generates an HTML which only contains the following.

Documize Export
Wed Jan 29 07:59:58 2020
No documents found

This applies to both the self-hosted or Documize cloud.

Am I missing something or is this a bug. I tried it as a user who set up the documize instance and also created a second User with Admin rights.

If I'm selecting Documents at space level as described at the docs it works, only exporting everything seems not to work.

**Comment by HarveyKandola** [comment]
Do the same documents export when you select category for export?

**Comment by Verbat** [comment]
Exporting categories works as intended. I'm just running into this problem when I try to export all.

**Comment by sauls8t** [comment]
Can you send some screenshots to supportATdocumizeDOTcom ?

**Comment by HarveyKandola** [comment]
Fixed for next release.
