### ISSUE TITLE
Documize gets stuck importing documents

### ISSUE THREAD

**Issue by asterlab** [documize/community#362]
It happens with docx, xls, csv and pdf documents, it gets stuck on importing document.

**Comment by HarveyKandola** [comment]
Are you running self-hosted on your server? Did you specify your own Conversion service endpoint?

https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/customizing-documize?currentPageId=WS3-rjltKgABVdLe

**Comment by asterlab** [comment]
the service is self hosted 
the docker is now installed and works 
[ https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/general-options | https://docs.documize.com/s/WNEpptWJ9AABRnha/administration-guides/d/WO0pt_MXigAB6sJ7/general-options ] 
got no 5010 port how can I enable it ? 

Renato Gallo

**Comment by HarveyKandola** [comment]
You can choose your own port number when you start Docker.

https://hub.docker.com/r/documize/conversion

**Comment by asterlab** [comment]
root@DOCUMIZE:/var/log# docker exec -it conversion /bin/bash 
root@8a1d0c093c8c:/documize# locate documize-pdf.log 
root@8a1d0c093c8c:/documize# 


Renato Gallo

**Comment by asterlab** [comment]
Plus I am still stuck at 


Renato Gallo

**Comment by asterlab** [comment]
I wrote [ http://documize.localdomain.domain:8080/ | http://documize.localdomain.domain:8080 ] 




Renato Gallo

**Comment by asterlab** [comment]
bump ?

**Comment by HarveyKandola** [comment]
Go to this URL and tell me what you see:

http://documize.localdomain.domain:8080/api/version

Just checking to see if your conversion service is working ok.

**Comment by asterlab** [comment]
3.1.0 

Renato Gallo

**Comment by HarveyKandola** [comment]
It is also recommended that Docker be given the IP address of your DNS server to help with domain name resolution (note the --dns switch):

docker run -d --name="documize-conversion" -p 8080:80 --dns=DNS_SERVER_IP documize/conversion:3.1.0

**Comment by asterlab** [comment]
Hello, 

"docker run -d --name="documize-conversion" -p 8080:80 --dns=DNS_SERVER_IP documize/conversion:3.1.0 " That I did. 
Just to be sure, knowing that the intranet documentation site url is documize.localdomain.domain which url should I place in the configuration box? https://documize.localdomain.domain:8080 ? [ http://documize.localdomain.domain:8080/ | http://documize.localdomain.domain:8080 ] ? 
Is there a path I should add to the url ? 
Is there a way to use a debian vm instead of docker ? 

Renato Gallo

**Comment by asterlab** [comment]
add that there's no such a thing as a documize-pdf.log inside the docker 

Renato Gallo

**Comment by asterlab** [comment]
now it's allright... how can i do so that the docker starts at boot with systemd

**Comment by HarveyKandola** [comment]
https://docs.docker.com/config/daemon/systemd/

**Comment by asterlab** [comment]
I have meant can you correct my documize-conversion.service showing me what's wrong ?

**Comment by HarveyKandola** [comment]
We have this for Documize:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/installation-guide?currentPageId=bottk82ahngfppc3i91g

As for Docker -- you should consult their documentation.

**Comment by asterlab** [comment]
can't you please just review the service I have ?
