### ISSUE TITLE
File is too big to be uploaded

### ISSUE THREAD

**Issue by asterlab** [documize/community#364]
How can I change the maximum 250M size of a file that can be uploaded to an article ?

**Comment by HarveyKandola** [comment]
That might depend on your database provider -- what is it?

Would never advise attachments that large!

**Comment by HarveyKandola** [comment]
This might help you:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V2KuM8ICcQABagM5/database-tuning

**Comment by asterlab** [comment]
I am the db provider

**Comment by HarveyKandola** [comment]
DB provider as in database type -- MySQL, etc.

**Comment by asterlab** [comment]
exactly which parameter should I increase ? (usually there's a php.ini to touch)
