### ISSUE TITLE
Public access seems not possible

### ISSUE THREAD

**Issue by karl007** [documize/community#371]
We want to use documize in our Organization. ldap authentication works great, but it seems that Nothing is accessible public.

`Public Spaces Viewable By Anonymous Users` is enabled
![image](https://user-images.githubusercontent.com/3982450/75100106-de06da80-55c9-11ea-9455-f22b895e1839.png)
 and I have spaces with the `view` permission for user `Everyone`
![image](https://user-images.githubusercontent.com/3982450/75100110-f8d94f00-55c9-11ea-9b74-15d26ae84b29.png)
, but on the start page shows a login page and also deep links to documents don't work.

What could be wrong?
---
Documize Community v3.7

**Comment by karl007** [comment]
I thought the problem was through LDAP authentication, but changed to Documize does not change the Problem. Also upgrade to 3.7 change anything.

**Comment by HarveyKandola** [comment]
Public access is not possible with LDAP auth.

**Comment by karl007** [comment]
thanks for the fast response. Maybe this should be added to the doc or better disable the setting in ldap auth? (or did I overread this?)

The weird thing is, thath after I change the authmode back to documize, there was also no public access. Is this disabled after used the ldap auth once?

Is there a plan to allow public access with ldap in the future? Or is there something like a workaround?

**Comment by HarveyKandola** [comment]
So, I doubt we will implement anon-access on installations that are using LDAP -- those tend to be "enterprise" deployments and hence anon-access is a very dangerous thing!

That being said, the setting in question should not even be visible when using LDAP -- you are right.

When using regular Documize auth then anon-access should work just fine. Example is our own public docs https://docs.documize.com
