### ISSUE TITLE
[Bug Report] Dual login fails when LDAP fails

### ISSUE THREAD

**Issue by kahoowkh** [documize/community#374]
### Background:
**Community Edition v3.7.0 (build 200204130935)**

I'm using LDAP as the Authentication method. But recently, I've changed something in my LDAP server, so I would like to change the config in Documize. 

I've created an Admin account with "regular Documize email/password" before, and dual login is enabled. 

![image](https://user-images.githubusercontent.com/26565078/76182593-7030f480-6200-11ea-8edf-c1f86a773176.png)

However, I'm not able to login with that account either.

### Expected result:
Will be able to login with accounts which is not using LDAP.

### Actual result:
Fail to login with accounts which is not using LDAP.

### Workaround:
Go to the database and edit the LDAP config data directly.
`dmz_org` -> `c_authconfig`

**Comment by HarveyKandola** [comment]
Please can you contact supportATdocumizeDOTcom -- have some questions that will require you to disclose further information.
