### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by jamesbeedy** [documize/community#40]
Trying to install documize on ubuntu, I can't seem to get any version of mysql or percona to work.

To reproduce: Install mysql on ubuntu, and configure documize to use it, following which you should see:

<img width="1440" alt="screen shot 2016-10-08 at 2 46 04 pm" src="https://cloud.githubusercontent.com/assets/5590546/19216147/258a1c12-8d66-11e6-8caa-f857bb9e7a24.png">

**Comment by HarveyKandola** [comment]
@jamesbeedy let me check and get back to you with a solution this weekend

**Comment by HarveyKandola** [comment]
@jamesbeedy this should be resolved in latest release

**Comment by jamesbeedy** [comment]
@harveykandola awesome! Thanks!
