### ISSUE TITLE
Support for percona/extradb

### ISSUE THREAD

**Issue by jamesbeedy** [documize/community#42]
Documize errors when percona is used as a backend.

<img width="1438" alt="screen shot 2016-10-10 at 10 15 46 am" src="https://cloud.githubusercontent.com/assets/5590546/19244742/9a1b5006-8ed2-11e6-9d53-2404ccb0d8e5.png">

**Comment by jamesbeedy** [comment]
@HarveyKandola I wrote a "charm" for documize [here](https://github.com/jamesbeedy/charm-documize)

I most commonly use percona with XtraDB engine as my mysql solution. Do you think we can add the bits for percona to the database detection mechanism?

Thx

Percona -> https://jujucharms.com/percona-cluster/xenial/2

**Comment by HarveyKandola** [comment]
@jamesbeedy love the charm!

Percona verison detection code -- it's just that Documize needs MySQL 5.7.10 or above because we use JSON column types. Assumption: you are running 5.6.21 which probably does not have JSON column types.

Nonetheless, we should improve the messaging to explain that!

**Comment by jamesbeedy** [comment]
@HarveyKandola looks like its hard-coded into the config -> https://github.com/openstack/charm-percona-cluster/blob/master/hooks/percona_utils.py#L77

From the sound of it I'll have to wait until canonical packages percona 5.7 -> http://paste.ubuntu.com/23304929/, http://paste.ubuntu.com/23304934/

The second link is what shows in xenial once the percona source repo is added. 

The percona charm is easy enough to patch to make it work with percona repo packages for 5.7 bc the charm offers custom package source config, just needs the pkg names patched up to match in the hard-coded part.

**Comment by HarveyKandola** [comment]
We have support for Percona Server database.
