### ISSUE TITLE
Feature Request: Support setting email server config in gui

### ISSUE THREAD

**Issue by jamesbeedy** [documize/community#45]
It would be nice to have the capability to set the email server configs from the gui.

**Comment by EnesAlili** [comment]
hey @jamesbeedy we are currently working on this. We will let you know when its ready : )

**Comment by HarveyKandola** [comment]
After upgrading to 0.27 you should run the following command to set who is a global admin:

```
UPDATE user SET global=1 WHERE refid='YOUR-USER-ID-HERE';
```
