### ISSUE TITLE
Documize breaks everytime mysql version gets bumped

### ISSUE THREAD

**Issue by jamesbeedy** [documize/community#50]
Request for better regex matching for mysql version.... documize broken due to this mysql version regex mismatch. This is happening with latest stable mysql in Xenial ubuntu source pkg repos.

![screen shot 2016-10-21 at 11 02 42 am](https://cloud.githubusercontent.com/assets/5590546/19607335/f2358a1e-977d-11e6-8e5c-4f294764131e.png)

**Comment by HarveyKandola** [comment]
Any update on this issue?

Latest release does not contain that error message so we think it might be an old release that contained the issue.

**Comment by jamesbeedy** [comment]
@HarveyKandola totally was 😀
