### ISSUE TITLE
Move files (images) to external file and link from database

### ISSUE THREAD

**Issue by patoroco** [documize/community#72]
Hi,

I'm looking for a great tool to move our documentation (currently we're using github wiki, but it doesn't have some features like search, upload images, etc), and I started to try documize.

It looks really good, but after some research in mysql data, I saw that an image which I uploaded to a page was stored directly in database.

With 10 pages and 2-3 images it runs perfect, but I'm worried about whether this affects performance. Could you confirm that on this way I will be able to store several pages, with images and files without performance problems?

Thanks!

**Comment by HarveyKandola** [comment]
Jorge,

In our previous startup (and sister product, https://www.countersoft.com) we did the same thing -- database contains everything including images:

1. It simplifies backup, restore, export, disaster recovery, upgrading.
2. We saw no slowdown in a battle-tested environment: thousands of enterprise customers with significant deployments.
3. Having "self-enclosed" data provides options for embedding, exporting.

IMHO, it should be just fine. Hope this answers the question.

**Comment by patoroco** [comment]
Oh, thanks for your quick answer @HarveyKandola!

Only I suspected that if database needs to send too much data to "go process", and from here to nginx (if you have a proxy over there), it would block a worker more time.

As I told, this was more a feeling from me, but I don't have scientific answer either because I never tried it (I can remember that CoreData in iOS allows to store files directly in the database, but it automatically move to file system if the file is over 1MB).



Thanks!
