### ISSUE TITLE
Export pages, it's possible?

### ISSUE THREAD

**Issue by patoroco** [documize/community#73]
Hi,

there is any way to export all data (pages and files) in a comfortable way? I mean, export to markdown, XML or something else if we need to move to another host or whatever.

Thanks!

**Comment by HarveyKandola** [comment]
Export is the list -- just need opinions from the community regarding scope (all docs? all spaces?) and format...

**Comment by patoroco** [comment]
OK, in our case is only to be sure that we'll never lose our documents (to have "obfuscate" in database is more or less like to lose) if we decide to move from one server to another, or if documize cut the support for example (I pray to don't happen that :P)

**Comment by HarveyKandola** [comment]
No obfuscation -- just pull data from ```document``` and ```page``` tables. See the ```page.body``` field for formatted HTML data.

In case you want raw data see the ```pagemeta.rawBody``` field.

**Comment by patoroco** [comment]
Oh, nice!

I was looking `document` and `page` table, but I hadn't understood `pagemeta` scheme.

Currently I have some documents that were imported from `.md` files (from our wiki in github), and in the `pagemeta.rawBody` they appear as encoded HTML.
On the other side, in the `document.location` appears a path for the file which was imported (something like: `/var/folders/m0/ptm5x6ms58x5tx3j1n9v7zjm0000gn/T/documize/_uploads/dbbddb37-843a-4759-5088-3f242c465de0/mydocument.md`), but when I try to access here, it isn't here, so I suppose that documize imports it, and after process the content, file is deleted, isn't it?

**Comment by HarveyKandola** [comment]
If you add a Markdown section to a document through the UI, then ```pagemeta.rawBody``` contains the actual Markdown text. The converted HTML is held in ```page.body``` which is rendered.

To view the contents of ```pagemeta.rawBody```  use this query:

```select CAST(rawBody AS CHAR(10000) CHARACTER SET utf8) from pagemeta where documentid='xxx';```

The difference is when you import a Markdown document -- it gets converted and imported as HTML.

In terms of the import location -- this is deleted after import.

**Comment by HarveyKandola** [comment]
In terms of exporting, we think a zip file should be sufficient containing raw and formatted data as well attachments.

If you export a space then all documents within that space would be in the zip file.

If you export everything in your Documize instance, then the zip file will have all documents organized by space.

We have no plans to obfuscate the data because it affects SQL querying and tinkering with no added benefit.

Hope this helps.

**Comment by HarveyKandola** [comment]
This is now complete -- export documentation to self contained HTML file.

Callable from API.

Filter by Spaces, Categories or selected Documents.
