### ISSUE TITLE
Support for mariadb

### ISSUE THREAD

**Issue by MorphBonehunter** [documize/community#74]
As MariaDB is widely seen as the MySQL replacement (and major Linux dists use it as standard now), it would great if this is supported.

It is an similar request to #42 .

**Comment by HarveyKandola** [comment]
Percona support now enabled in Master.

As for MariaDB, Documize requires JSON column types which are in MySQL/Percona 5.7.10+. I think they are present in MariDB 10.2+ onwards but still waiting for official Docker image for that release before proceeding with tests against MariaDB 10.2+

**Comment by MorphBonehunter** [comment]
Ok, i make an false assumption as i thought MariDB already supports JSON Data Type (i mistake the connect engine with the json table type).
So i take a look at it again and found this one: https://jira.mariadb.org/browse/MDEV-9056
At the moment i fear JSON Support isn't ready for 10.2. :(

**Comment by HarveyKandola** [comment]
Yup, that is the same issue we looked at as well.

If MariaDB is a drop-in replacement for MySQL 5.7+ then they need to have a JSON column type.

I will keep this issue open.

**Comment by lchanouha** [comment]
Hi,
MariaDB 10.2 (stable) was released this month with JSON support.

But syntax is different as of this article: https://mariadb.com/resources/blog/json-mariadb-102
attr VARCHAR(1024),   CHECK (JSON_VALID(attr)));

**Comment by HarveyKandola** [comment]
Great, we will test and report back.

At first glance, the syntax in questions seems to be a bespoke MariaDB constraint check that Documize might not need to utilize.

**Comment by HarveyKandola** [comment]
It looks like MariaDB DDL does not support JSON column type -- instead they have chosen to provide a bunch of JSON related functions that work over existing columns types (e.g. VARCHAR).

They might (and should) introduce at some point a lightweight DDL compatible solution.

So at this point, we have to wait.

**Comment by MorphBonehunter** [comment]
As it is not clear if and when such an solution will be implemented in MariaDB i close this and maybe come back to this later.

**Comment by HarveyKandola** [comment]
See #102 -- implementing for next release!
