### ISSUE TITLE
reverse proxy support

### ISSUE THREAD

**Issue by bryfry** [documize/community#75]
Apologies if I'm not reading the docs correctly.  I'd like to run documize behind a reverse proxy (e.g. at example.com/wiki).  Default configuration the page renders blank because of lots of requests to /assets and /codemirror.

Thanks for any help!

**Comment by HarveyKandola** [comment]
Would you like to use something like NGINX in front of Documize?

**Comment by bryfry** [comment]
yep, that is exactly what I am trying to do

**Comment by HarveyKandola** [comment]
You could try to put something like this in nginx.conf:

```
location /codemirror/ {
    proxy_pass http://localhost:5001;
    proxy_redirect off;
}
location /assets/ {
    proxy_pass http://localhost:5001;
    proxy_redirect off;
}
location /sections/ {
    proxy_pass http://localhost:5001;
    proxy_redirect off;
}
location /tinymce/ {
    proxy_pass http://localhost:5001;
    proxy_redirect off;
}
location ~*favicon {
    proxy_pass http://localhost:5001;
    proxy_redirect off;
}
```

**Comment by nrstmss** [comment]
sd

**Comment by mistergibson** [comment]
This is rather horrid reverse proxy support. you need to allow us to set an INTERNALLY referenced site PREFIX for ALL generated URLs.
