### ISSUE TITLE
add tag window not responsive

### ISSUE THREAD

**Issue by nikit-nl** [documize/community#88]
When adding the first tag to a document the window falls have outside of the browser windows
![issuedocumize](https://cloud.githubusercontent.com/assets/26732855/24391240/27294814-138e-11e7-9aa2-b545b526cc85.png)

**Comment by HarveyKandola** [comment]
Thanks for the report @nikit-nl -- fixed and commited.

New binary release due later today.

**Comment by HarveyKandola** [comment]
Please download and use latest release!
