### ISSUE TITLE
Unable to send email error=EOF

### ISSUE THREAD

**Issue by au-re** [documize/community#93]
Hi, I run into this issue when adding a user in user management after setting up documize locally. I have configured the "Mail Server Settings" according to the documentation and the same configuration works fine in another server that I am running locally. What could be causing this?

`
ERRO[0330] InviteExistingUser - unable to send email     env=Non-production error=EOF stack=goroutine 361 [running]:
github.com/documize/community/core/log.Error(0xc4202905d0, 0x29, 0xf4a240, 0xc420014120)
	src/github.com/documize/community/core/log/logger.go:64 +0xab
github.com/documize/community/core/api/mail.InviteExistingUser(0xc42023d1c0, 0x16, 0xc4203e2d20, 0x11, 0xc4203e2d40, 0x16)
	src/github.com/documize/community/core/api/mail/mailer.go:121 +0x760
created by github.com/documize/community/core/api/endpoint.AddUser
	src/github.com/documize/community/core/api/endpoint/user_endpoint.go:189 +0x93b
`

**Comment by HarveyKandola** [comment]
It could be an issue with the port number.

For example, with GMAIL I would use port 587 and not the 465 TLS port.

**Comment by au-re** [comment]
Thanks for the quick reply! I am using amazons SES and the port for it is 465. If the port was set wrong wouldn't the connection simply time out?

**Comment by HarveyKandola** [comment]
_If the port was set wrong wouldn't the connection simply time out?_

You would have thought so!

Switch to port 587 and let me know if it works.

**Comment by au-re** [comment]
I've set the port to 587 and no error shows up, however no email is sent either. I am able to send emails using the same credentials from another server on port 465.

**Comment by HarveyKandola** [comment]
Got it.

We'll troubleshoot SES and report back ASAP.

**Comment by HarveyKandola** [comment]
Can you confirm if your AWS SES account is out of sandbox mode? You will find this under SES Management Console -> Sending Statistics.

![image](https://cloud.githubusercontent.com/assets/971717/25442913/35903652-2a9e-11e7-8252-6c62afb81529.png)

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html

When in sandbox mode, every sending and receiving address needs to be verified.

**Comment by au-re** [comment]
Thanks the tip, I double checked and SES is not in sandbox mode. Gona try some other SMTP service to make sure I'm not doing something silly and I'll get back to you.

**Comment by HarveyKandola** [comment]
Please upgrade to latest release!
