### ISSUE TITLE
Install for linux and mac not working.

### ISSUE THREAD

**Issue by enyosolutions** [documize/community#97]
The file that come from your website have no extension and does not open as an archive or an executable...

**Comment by HarveyKandola** [comment]
The files in question are not "packages" or "installation" files -- they are the actual Documize software executables.

To be clear:

https://docs.documize.com/s/VzO9ZqMOCgABGyfW/installation-guides/d/V16L08ucxwABhZF6/binary-installation-guide

**Comment by spectrumzhang** [comment]
marked
