### ISSUE TITLE
Spaces not displayed on settings page

### ISSUE THREAD

**Issue by gala132** [documize/community#99]
Hi!
After installing the app and while accessing the url `/settings/folders` I can not see any spaces, although there are a few already defined.
The list is empty and in the console we get a `t.map is not a function` error like in the screenshot below.

![Error screenshot](https://p1.picsto.re/H9fTG.png)

**Comment by HarveyKandola** [comment]
Looking into this now and will report back!

**Comment by HarveyKandola** [comment]
More than likely you have no shared spaces -- only personal spaces?

New build will be out later today -- please upgrade and test.

**Comment by gala132** [comment]
That may be possible, but if I do not have any it would be maybe better to display some message that would indicate it that and not just a list header with empty body. (That is just my opinion, but this way the user would be noticed about the state of this.)

**Comment by HarveyKandola** [comment]
100% correct, change made for next release!

**Comment by HarveyKandola** [comment]
https://github.com/documize/community/releases/tag/v1.48.1
